### ISSUE TITLE
Saleor ran into an unexpected problem

### ISSUE THREAD

**Issue by YufanWu147** [saleor/saleor-dashboard#1009]
When I tried to log in to the dashboard, there's a message said "Saleor ran into an unexpected problem".

Below is a screenshot of the error messages in the chrome development tool.

![image](https://user-images.githubusercontent.com/43006202/110988079-10eb5000-833e-11eb-9101-6da8ecffc28c.png)

Please help me look into this, thanks!

**Comment by krzysztofwolski** [comment]
Did you setup properly Allowed Hosts in your Core? https://docs.saleor.io/docs/3.0/developer/running-saleor/configuration#allowed_hosts

**Comment by eCzerniak** [comment]
Could not reproduce this bug. @YufanWu147  if you still have this problem please reopen and give more information.
