### ISSUE TITLE
can't type in email/password inputs after log out

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor-dashboard#1025]
Steps:
1. Login
2. Log out
3. Try to type in credentials, it won't type

**Comment by krzysztofwolski** [comment]
@LeOndaz which version do you use?

**Comment by LeOndaz** [comment]
I don't really remember, this is relatively old. It was the latest with respect to the bug date

**Comment by eCzerniak** [comment]
I'm trying to reproduce this bug on 3.0 version and I can not achieve your result. @LeOndaz  do you still have this problem? If yes could you please give more information about saleor version and browser which you are using?

**Comment by eCzerniak** [comment]
I'm closing this issue, if this problem will occurs once more please open new ticket with more information. 
Regards.
