### ISSUE TITLE
DraftJS editor issue with typing certain letters

### ISSUE THREAD

**Issue by Sarowar-neo** [saleor/saleor-dashboard#1047]
![Screenshot from 2021-04-02 03-11-57](https://user-images.githubusercontent.com/22500875/113354639-47c2ed80-9361-11eb-8653-dce23b62df45.png)

**Comment by hthieu1110** [comment]
Hi,
I face this problem also. Cannot type some chars like u, i .... Any one has found some solutions ?

Thanks.

**Comment by Cloud11PL** [comment]
Hi @Sarowar-neo , @hthieu1110, is this still an issue?

**Comment by eCzerniak** [comment]
If this problem will occurs once more please open new ticket. For this moment I am closing it. 
Regards.
