### ISSUE TITLE
Add SKU column to catalog product listing

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor-dashboard#1085]
### What I'm trying to achieve
It would be very helpful if the Catalog -> Products listing included the option to output a column for SKU.

### Describe a proposed solution
When the SKU column was selected, it should show the top X SKUs (maybe in a comma separated list) that are associated with the given product. Not sure how many would make sense here; depends on the space available.

Attributes are useful, but SKUs are how most people internally know our products, so it would be very nice to be able to see them at a glance.

**Comment by onecrayon** [comment]
This is a feature request; it is not stale.

**Comment by onecrayon** [comment]
This is a feature request; not stale.

**Comment by timuric** [comment]
We will address this when the Datagrid UI arrives #2083
