### ISSUE TITLE
Link product names in list to allow opening in new tab

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor-dashboard#1087]
### What I'm trying to achieve
Currently you cannot easily open a new tab for a product detail page when browsing the products listing in the Dashboard, because it's not linked.

### Describe a proposed solution
Wrap the product name (or the entire row?) in a link, so that you can open it in a new tab, if desired.

**Comment by onecrayon** [comment]
Not stale; this is a feature request.

**Comment by onecrayon** [comment]
Still a feature request.

**Comment by jwm0** [comment]
Hey @onecrayon, this is on our internal roadmap as something we'd also like to tackle in 3.0. Unfortunately, it's a tedious task that will be difficult to automate and will require to wrap all navigation buttons in `a` tags and move the routing logic, so it's yet to be fully planned but definitely agree with that one.

**Comment by timuric** [comment]
This was shipped in 3.4
