### ISSUE TITLE
Page scrolls to top when tapping "assign references"

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor-dashboard#1089]
### What I'm trying to achieve
When picking references for a reference type attribute, the dashboard scrolls to the top of the page when they are assigned. It would be nice if the scroll position were maintained instead.

**System information**

Saleor version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by eCzerniak** [comment]
@onecrayon it is fixed (version 3.0.0.-b.19) so I am closing this issue :)
