### ISSUE TITLE
Adding unpublished products to an order results in an unknown error

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor-dashboard#1128]
Steps:
1. Create a product, don't publish it, be sure it's added to a channel
2. Create an order on the same channel, add the product

![image](https://user-images.githubusercontent.com/17862017/119820686-0d557700-bef2-11eb-9676-7fe18cde1d51.png)

**Comment by eCzerniak** [comment]
This issue is fixed.
https://github.com/saleor/saleor-dashboard/pull/1921
