### ISSUE TITLE
PRODUCT_NOT_PUBLISHED not handled by orderLinesCreate dashboard logic

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor-dashboard#1194]
### What I'm trying to achieve
When creating an Order draft, trying to add a product that is not published in the current active channel results in "Unknown Error" being displayed.

### Steps to reproduce the problem
1. Set the "is published" flag for a product to false in the current channel
2. Create a new Order draft
3. Try to add the product

### What I expected to happen
A human readable error message.

### Http request and response from inspector

Response:
```
{"data": {"orderLinesCreate": {"errors": [{"code": "PRODUCT_NOT_PUBLISHED", "field": "input", "addressType": null, "__typename": "OrderError"}], "order": null, "__typename": "OrderLinesCreate"}}}
```

**System information**

Saleor version:
- [ ] dev (current master)
- [x] 3.0 (a33)
- [ ] 2.11
- [ ] 2.10

**Comment by krzysztofwolski** [comment]
Theres a bug in product selection modal - unpublished products should not be displayed here. Fix for that is in the making.

**Comment by szczecha** [comment]
I retested this issue on a fresh build
dashboard v3.4.0-dev
core v3.5.0-a

It was fixed. 
User can't select unpublished products in Draft Order/Add product
