### ISSUE TITLE
Saleor cors issue on dashboard

### ISSUE THREAD

**Issue by Tjajeer** [saleor/saleor-dashboard#1225]
### What I'm trying to achieve
…
I m trying to connect the frontend dashboard with the backend, gettings cors issue from a branch -  3.0 on both the repos
<img width="1440" alt="Screenshot 2021-07-11 at 3 11 35 PM" src="https://user-images.githubusercontent.com/19812539/125190362-5ff8b180-e25a-11eb-8a66-5c0696ca6fe9.png">

### Steps to reproduce the problem
.env file on frontend

API_URI=http://localhost:8000/graphql/
APP_MOUNT_URI=http://localhost:9000/dashboard/
STATIC_URL=http://localhost:9000/

Saleor version:
- [x] 3.0

Operating system: 
- [x] MacOS

Browser:
- [x] Safari
- [x] Chrome
- [x] Edge
- [x] Other

**Comment by kevcal69** [comment]
@Tjajeer add "authorization-bearer" in CORS_ALLOW_HEADERS on django settings. 

`
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "authorization-bearer",
]
`
spent a lot of time with this.

**Comment by mituBarua** [comment]
any one solved this issue?

**Comment by Megidd** [comment]
> CORS_ALLOW_HEADERS

Which file did you change?

**Comment by kevcal69** [comment]
@Megidd django settings file. If its set just add the header if its not copy the whole settings variable above.

**Comment by timuric** [comment]
Added instruction to the README https://github.com/saleor/saleor-dashboard/pull/2101
