### ISSUE TITLE
I connect to the dashboard and after 5 seconds it disconnects me

### ISSUE THREAD

**Issue by ionut98G** [saleor/saleor-dashboard#1249]
### What I'm trying to achieve
I connect to the dashboard and after 5 seconds it disconnects me.

This dashboard it s on to heroku!

Version: 2.11.0

![image](https://user-images.githubusercontent.com/86763563/126430612-3ba7c9cd-6e25-417a-9d49-99db040903a8.png)

**Comment by krzysztofwolski** [comment]
Hello, can you provide the response error from the networking tab?

**Comment by eCzerniak** [comment]
@ionut98G Does this problem still occur?
