### ISSUE TITLE
Dashboard locally not working with graphql

### ISSUE THREAD

**Issue by philipgierszal** [saleor/saleor-dashboard#1362]
### What I'm trying to achieve
Start the website with npm start

### Steps to reproduce the problem
1.  Download a fresh version 2.11
2.  Set the NEXT_PUBLIC_API_URI = https://graphql.my.Website/graphql/

Error: Network error: Response not successful: Received status code 400
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
new ApolloError
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (92:26)
<unknown>
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (1588:34)
<unknown>
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (2008:15)
Set.forEach
<anonymous>
<unknown>
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (2006:26)
Map.forEach
<anonymous>
QueryManager.broadcastQueries
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (2004:20)
<unknown>
file:///D:/Work/Nico/SaleorNice/update/saleor-storefront/node_modules/apollo-client/bundle.umd.js (1483:29)
runMicrotasks
<anonymous>
processTicksAndRejections
internal/process/task_queues.js (93:5)

**Comment by KristofTomase** [comment]
Hey Did You fixed that ?
Mvh,
Kristof

**Comment by GiuseppeCrBrandi** [comment]
same error here.... still not a clue
