### ISSUE TITLE
Stripe plugin: Webhook field?

### ISSUE THREAD

**Issue by gleniat** [saleor/saleor-dashboard#1523]
### What I'm trying to achieve
Fill the `Webhook endpoint` input field or see the instructions how to get it filled. I can click in the input, but I can't type anything.

### Steps to reproduce the problem
1. Activate Stripe plugin in Saleor Dashboard.
2. open Stripe plugin settings
3. click in `Webhook endpoint` field and try to type something

### What I expected to happen
Instructions what to do to get the field filled in. Current label `Unique identifier for the webhook endpoint object.` is not clear enough.

### Screenshots
![2021-10-19_20-35-28](https://user-images.githubusercontent.com/70897052/137971600-0b5f8d62-696e-4607-8563-3f865d74dba9.gif)

**System information**

Saleor + Saleor Dashboard version:
- [x] dev (current main)
- [x] 3.0beta
- [x] 3.0alpha

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by epoq** [comment]
Hello @gleniat ,first of all sorry for my english!
according to documentation and my personal experience the webhook are automatically subscribe by Saleor Core:

link [here](https://docs.saleor.io/docs/3.0/developer/available-plugins/stripe#stripe-webhooks)

No need to add the weebhook secret if is your question !
i hope my answer helps you !
