### ISSUE TITLE
Runtime Variables

### ISSUE THREAD

**Issue by demux** [saleor/saleor-dashboard#1592]
Having to build a new version of the app each time the url changes, i.e. having to build a new docker image for each environment is very inconvenient. I would like the app to take these variables at runtime and not at build time.

**Comment by jwm0** [comment]
Hi @demux, I see the advantages of this solution but we have no plans to introduce it in the near future. If your workflow would benefit from this significantly then this seems like an easy fork to maintain on your side as you would be essentially only modifying the `config.ts` and `index.html` files while adding some scripts of your own to inject it during runtime.
