### ISSUE TITLE
Dashboard crash with graphql API created product

### ISSUE THREAD

**Issue by fxp** [saleor/saleor-dashboard#1674]
### What I'm trying to achieve
I'm trying to import product data into a new 3.1  core and dashboard.

### Steps to reproduce the problem
1. Create a new Product Type in dashboard (No variance, Simple product) (I used "Beer" created with "python3 manage.py populatedb")
2. Create a product with that Product Type (Beer) via Graphql 
3. Enter detail page of that product just created
4. Dashboard crashed

### What I expected to happen
1. It's should be a normal product detail page

### Screenshots
![Screen Shot 2021-12-09 at 11 11 18 AM](https://user-images.githubusercontent.com/57029/145327937-2069f130-b593-4f86-883d-473336a4cad8.png)
![Screen Shot 2021-12-09 at 11 11 36 AM](https://user-images.githubusercontent.com/57029/145327952-9a299ea0-128a-46dc-ad70-8b1a5a686555.png)
![Screen Shot 2021-12-09 at 11 11 45 AM](https://user-images.githubusercontent.com/57029/145327977-af4570b9-b7a1-4a56-9406-91a7a0a8e95d.png)
![Screen Shot 2021-12-09 at 11 11 54 AM](https://user-images.githubusercontent.com/57029/145327980-c3a6015f-6358-4490-a9a2-978fce119c0a.png)

### Http request and response from inspector
All graphql API are ok (200)

### Console output
[127.0.0.1-1639019827925.log](https://github.com/saleor/saleor-dashboard/files/7681948/127.0.0.1-1639019827925.log)

**System information**

Saleor version:
3.1

Operating system: 
MacOS

Browser:
Chrome

**Comment by Cloud11PL** [comment]
Hi, can you provide us the query you used to create the product?

**Comment by eCzerniak** [comment]
I'm closing this issue because of missing information. If this problem still occurs please give all needed information (with mutation that is used for product create) and create new ticket. 
Regards.
