### ISSUE TITLE
How i can login to saleor admin?

### ISSUE THREAD

**Issue by PeaceAntoHim** [saleor/saleor-dashboard#1888]
### What I'm trying to achieve
…

### Describe a proposed solution
...
![Screenshot 2022-02-21 114313](https://user-images.githubusercontent.com/86556550/155258081-881f1ed7-e879-4584-b3eb-d03f9bc6af5f.png)

### Other solutions I've tried and won't work
…

**Comment by timuric** [comment]
Seems like you are not running Saleor core server
