### ISSUE TITLE
Color code Input error for Swatch Value

### ISSUE THREAD

**Issue by antran22** [saleor/saleor-dashboard#1925]
### What I'm trying to achieve
I'm trying to set the color code of a Swatch Attribute value.

### Steps to reproduce the problem
1. Create a new Swatch Attribute in Configuration/Attributes
2. Assign Value
3. Set Color code value as Hex or as RGB

### What I expected to happen
I can set the Hex value or the RGB value accordingly

### Screenshots
<img width="487" alt="image" src="https://user-images.githubusercontent.com/22423559/158043535-f2877e6e-e196-4cf9-951d-736e430c9e38.png">
I cannot set the Hex value completely. This is due to the `maxLength` props being set to 6 [in this file](https://github.com/saleor/saleor-dashboard/blob/6d9d35379971733f4b148dbcdb969c913c43c9c2/src/components/ColorPicker/ColorPicker.tsx#L146), while it should be 7 to account for the pound sign (#)

I cannot also set the RGB values separately, whenever I set one others is set to 0. This is because of this incorrect implementation of the [handleRGBChange function](https://github.com/saleor/saleor-dashboard/blob/6d9d35379971733f4b148dbcdb969c913c43c9c2/src/components/ColorPicker/ColorPicker.tsx#L62), where it should take into account old `r, g, b` states.

I can create a new PR for a fix.

### System information

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Other

**Comment by timuric** [comment]
Fixed in the next release
