### ISSUE TITLE
Do NOT override `Ctrl` + `Tab` shortcut!

### ISSUE THREAD

**Issue by 416d72** [saleor/saleor-dashboard#1942]
### What I'm trying to achieve
Remove this bad UX

### Steps to reproduce the problem
1. Open any page
2. Hit `Ctrl` + `Tab` to switch the browser tab

### What I expected to happen
Ability to switch browser tabs

### Http request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

**System information**

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by timuric** [comment]
@416d72 we don't override this shortcut and neither we can reproduce this issue, could you provide more info? Perhaps are you using any chrome extensions?

**Comment by 416d72** [comment]
I was using Vivaldi back then but switched to Firefox recently and couldn't reproduce it either, perhaps Vivaldi was the issue.
