### ISSUE TITLE
Dashboard crashes when creating a product with variants

### ISSUE THREAD

**Issue by basedceo** [saleor/saleor-dashboard#1962]
### What I'm trying to achieve
…
create a custom product with variants (similar to the black hoodie with size variants)
### Steps to reproduce the problem
1. Create the variant attribute (in my case its digital storage sizes)
2. In the dashboard create a product type "Digital Storage" with storage size as a variant attribute and check the Variant Selection box
3. Create a new product with the type of "Digital Storage" 
4. Go to create variants for the product, choose the option "Create multiple variant via variant creator"
5. Select the first value (64gb) on prices and SKUs select the attribute and choose the option to Apply unique prices by attribute to each SKU, select warehouses, and Apply unique stock by attribute to each SKU
6. Back on product page when I click into the variant to add price options the dashboard crashes

### What I expected to happen
…
on step 6 I expect to be able to click back into the variant and set the price and availability instead of the store crashing, or maybe be able to set the price and availability when creating the variant.
### Screenshots

https://user-images.githubusercontent.com/99623735/160620316-b5e8f9ba-63d1-4f18-8d67-de2c51da722b.mp4

### Http request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.1.7
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [x] Other, Firefox
I should also add that this is a problem with version 3.1.4, version 3.0 doesn't seem to have this problem

**Comment by devenvyas** [comment]
I think this is happening when a product has more than one image. Variant object is frozen since Props are immutable and `sort()` method will sort in-place - hence the error. 

Here is the console log:

`react_devtools_backend.js:3973 The above error occurred in the <ProductVariantPage> component:
    in ProductVariantPage (created by ProductVariant)
    in ProductVariant (created by ProductVariant)
    in ProductVariant (created by Context.Consumer)
    in Route (created by Component)
    in Switch (created by Component)
    in Component (created by Context.Consumer)
    in Route (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in ErrorBoundary (created by Routes)
    in main (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by Routes)
    in Routes (created by App)
    in ExitFormDialogProvider (created by App)
    in ExternalAppProvider (created by App)
    in AppChannelProvider (created by App)
    in ShopProvider (created by App)
    in AuthProvider (created by App)
    in AppStateProvider (created by App)
    in BackgroundTasksProvider (created by App)
    in MessageManagerProvider (created by App)
    in IntlProvider (created by LocaleProvider)
    in LocaleProvider (created by App)
    in DateProvider (created by App)
    in vo (created by w7)
    in fo (created by w7)
    in ThemeProvider (created by w7)
    in w7 (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in ApolloProvider (created by App)
    in SaleorProvider (created by App)
    in App`

**Comment by timuric** [comment]
@basedceo we are working on a new variant creation flow that would address many UX flaws and bugs. It should be released a month from now. For now, I would advise creating variants manually one by one

**Comment by timuric** [comment]
Related #2083
