### ISSUE TITLE
Variants take on SKU name instead of variant name

### ISSUE THREAD

**Issue by basedceo** [saleor/saleor-dashboard#1963]
### What I'm trying to achieve
…
create a product with variants similar to the pre-defined ones (red hoodie similar to existing black hoodie)

### Steps to reproduce the problem
1. create a product with the type Top (clothing)
2. Create some variants using the create similar variant method (multi variant creation is very buggy btw, but I have a separate bug report open for that)
3. If you enter the sku for the variant and click save, it will name the variant after the sku, if you don't enter a sku it gets a long alpha-numeric name (possibly a variant ID)
4. this sku/variant name also shows in the storefront for the product, so its a very big problem as the customer will not understand what variant they are choosing

### What I expected to happen
The variant to have a more sensible name given to it automatically, such as the variant attributes value (that's what all the pre-made products seem to do), or have an option to specifically define the name of the variant in the dashboard.

### Screenshots

https://user-images.githubusercontent.com/99623735/160668043-a3f5eea7-9db0-4923-b79a-55162530f79c.mp4

### Http request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

**System information**

Saleor version:
- [ ] dev (current main)
- [ ] 3.0
- [x] 3.1.7
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [x] Other, Firefox
I should also add that this is a problem with version 3.1.4, version 3.0 doesn't seem to have this problem

**Comment by RyanTamulevicz** [comment]
I see you said that this issue is happening at 3.1.4 and 3.1.7, but I also had it at 3.1.0.

**Comment by basedceo** [comment]
@RyanTamulevicz yeah, if you downgrade to 3.0 it doesn't seem to have this problem, I'm guessing the issue was introduced in a more recent commit.

**Comment by RyanTamulevicz** [comment]
I can also confirm this isn't an issue with the dashboard directly it seems... Using Dashboard 3.0.0 and updated API Core, it still changes the variant names to the SKU

**Comment by timuric** [comment]
Related #2000
