### ISSUE TITLE
Product variants get non-readable names for humans that seem to be Base64 encoded values

### ISSUE THREAD

**Issue by rodolfojcj** [saleor/saleor-dashboard#2000]
### What I'm trying to achieve
Get, set and display human readable names for the variants of a product.

### Steps to reproduce the problem
In the dashboard, create a product and then create variants for it.

### What I expected to happen
A human readable name could be set for each variant of a product. At least, the dashboard should allow editing the product variant name.
Instead of that, a Base 64 encoded value is saved in the "name" column of the "product_productvariant" database table. Later, the dashboard web UI renders it as read only and [a store instance based on the `react-storefront` project](https://github.com/saleor/react-storefront) also renders those unreadable names to the end user.

### Screenshots
![product-variant-ugly-names](https://user-images.githubusercontent.com/458749/163898152-7d5dec81-7cb7-4ee8-bfd6-7787687e5dab.png)

![product-variants-ugly-names-sql-details](https://user-images.githubusercontent.com/458749/163898794-116745ba-f5f9-496d-9401-b1e0a7a52a85.png)

![react-storefront-renders-ugly-product-variant-names](https://user-images.githubusercontent.com/458749/163901092-928d5f74-1f53-4ab1-9057-ac033ccfd803.jpg)

**System information**

- Saleor dashboard version 3.1.5
- Saleor core version 3.1.9

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [x] Firefox
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by timuric** [comment]
@rodolfojcj thanks for reporting, it is already in our backlog. In the meantime, as a workaround, you can add SKU or choose Variant Selection Attributes before saving variant

**Comment by rodolfojcj** [comment]
Hello @timuric, you're welcome and thank you too for the feedback.

Do you an estimation about when this issue will be solved?

Regards.

**Comment by blackyzero** [comment]
+1
i am getting same.

<img width="1411" alt="Screen Shot 2022-06-01 at 10 05 05 PM" src="https://user-images.githubusercontent.com/4286063/171533353-0bb08db6-4351-4f41-9e48-4e7a6c5efbae.png">
.

**Comment by timuric** [comment]
@blackyzero we currently working on a new variant creation flow that would have spreadsheet UI and would allow editing names of the variants. Should be released in a few weeks from now
