### ISSUE TITLE
Shop url input removed from settings introduces a breaking change in Stripe gateway and maybe other plugins/apps

### ISSUE THREAD

**Issue by carlosa54** [saleor/saleor-dashboard#2049]
### What I'm trying to achieve
The store domain input field got removed in this [PR](https://github.com/saleor/saleor-dashboard/pull/1989) and I think that causes a breaking change for plugins like Stripe which depends on the Shop's domain to create the webhook endpoint in the backend [here](https://github.com/saleor/saleor/blob/9b88221ba8c270b183ef17f6288045fcbe1fee96/saleor/payment/gateways/stripe/stripe_api.py#L60-L77)

### Steps to reproduce the problem
1. Create a local environment using saleor-platform
2. Setup the Stripe plugin in the dashboard
3. Webhook endpoint won't work and there's no way to update through the Dashboard, other than manually do it through shell

### What I expected to happen
Being able to update the Store domain through the dashboard

### Http request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

**System information**

Saleor version:
- [x] dev (current main)
- [x] 3.3
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by carlosa54** [comment]
As an example the `Using ngrok` section of the docs won't work https://docs.saleor.io/docs/3.x/developer/running-saleor/exposing-instance#using-ngrok

**Comment by timuric** [comment]
@carlosa54 we are aware of this issue, for now as a workaround I would suggest setting this variable using graphql mutation
