### ISSUE TITLE
Setting entityType of attribute via dashboard, currently it is null.

### ISSUE THREAD

**Issue by ifigueroap** [saleor/saleor-dashboard#2069]
### What I'm trying to achieve
Create an attribute via saleor-dashboard that is equivalent to the creation via graphql.
When creating the attribute in the dashboard, the  `entityType` property is null, whereas via graphql the entity type can be set to `'PRODUCT'`.

### Steps to reproduce the problem
1. Create attribute in dashboard.
2. Retrieve it via graphql, and see that the `entityType` property is null.

### What I expected to happen
I expected the property to be `'PRODUCT'`, or for an option in the creation form to determine this value.

**System information**
Saleor dashboard version:
dashboard v3.0.1 core v3.0.4

Saleor version:
- [ ] dev (current main)
- [X] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [X] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [X] Chrome
- [ ] Edge
- [ ] Other

**Comment by timuric** [comment]
@ifigueroap it is no longer an issue in 3.4, please upgrade
