### ISSUE TITLE
Hex value for Swatch Attributes cannot be entered - only 5 characters allowed

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor-dashboard#2086]
### What I'm trying to achieve

Hello Saleor team!

We need to be able to enter a HEX value by hand / copy-pasting, when defining color values for a swatch attribute 'shade' in the Dashboard.

### Steps to reproduce the problem

Try and enter a 6 character HEX value by hand / copy-pasting when assigning a value for a swatch attribute.

### What I expected to happen

Entering 6 characters for Hex value and saving that value so it can be used for the 'shade' attribute.

This bug reduces user experience of our clients when they work on their webshops.

### Screenshots and logs

![attribute shade](https://user-images.githubusercontent.com/75638667/169976251-7c9459b5-e865-4924-ba43-f4414211a870.jpg)

**System information**
Saleor version:
- 3.3.8
Dashboard version: 
- 3.3.2

NOTE: This also happens on previous versions of the Dashboard.

**Comment by timuric** [comment]
PR https://github.com/saleor/saleor-dashboard/pull/2087
