### ISSUE TITLE
Checkboxes trigger link click instead of checking the box.

### ISSUE THREAD

**Issue by wileyknight** [saleor/saleor-dashboard#2089]
### What I'm trying to achieve
Select the checkbox for Product Attributes, Variant Attributes or Variant Selection. All checkboxes leave the page as a link instead of as a check.

### Steps to reproduce the problem
1. Click on any checkbox.
2. 

### What I expected to happen
Checkbox to be selected so other secondary actions can be performed.

**System information**

Saleor version:
- [ ] dev (current main)
- [X] 3.4.2
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [X] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other 
- [X] Firefox

**Comment by wileyknight** [comment]
![image](https://user-images.githubusercontent.com/20311272/173103344-8068c33c-1fa1-49cf-bb2b-56945dfb3100.png)

It might only be affecting the variants and the attributes.

**Comment by timuric** [comment]
@wileyknight I can't reproduce it, have you tried in other browsers?

**Comment by timuric** [comment]
Indeed this is an issue in Firefox

**Comment by timuric** [comment]
Internal task: [SALEOR-7278](https://app.clickup.com/t/2549495/SALEOR-7278)
