### ISSUE TITLE
Can't filter Products by a numeric attribute

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2142]
You can't filter by a numeric attribute on the Products screen.

Go to the Products screen on the demo dashboard:
https://demo.saleor.io/dashboard/products/
Go to Filters, select Length and enter 55 and then click Done at the top, nothing happens. Scroll down to see the "Choose a value" error message for the Length filter.

<img width="408" alt="Screen Shot 2022-07-06 at 9 23 36 pm" src="https://user-images.githubusercontent.com/10040020/177542709-34c4b09c-1d76-445b-8a6e-d121c26f4d40.png">

There doesn't seem to be any related network requests or console error messages.

dashboard v3.4.1
core v3.4.9

Browser:
Tested and observed on the latest Chrome and Firefox.

**Comment by timuric** [comment]
@simon-online we were able to reproduce it, we will put a high priority, thanks for reporting!
