### ISSUE TITLE
Filter Products by Channel displays an unexpected error screen

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2146]
To view product prices on the Products screen you need to filter by a channel. However an unexpected error screen appears when you attempt to filter the Products screen by Channel.

Go to the Products screen on the demo dashboard:
https://demo.saleor.io/dashboard/products/
Go to Filters, select Channel and one of the channel options and then click Done. An unexpected error screen then appears.

<img width="506" alt="Screen Shot 2022-07-07 at 1 52 22 pm" src="https://user-images.githubusercontent.com/10040020/177687292-baf8b245-5e5b-44dc-95b4-eb464c98b3a9.png">

We’ve encountered an unexpected error
Don’t worry we will fix it soon. Try to refresh the page or go back to dashboard.
ERROR ID
237cbb896fb644adb4d10c0b423756ac

In dev tools Network there is a canceled graphql request for ProductList.

<img width="909" alt="Screen Shot 2022-07-07 at 2 04 49 pm" src="https://user-images.githubusercontent.com/10040020/177688942-0a52fa25-321a-4408-a641-60f24f0cb138.png">

If I then go ahead and reload the page the Products screen appears with the Channel filter correctly applied.

dashboard v3.4.1
core v3.4.10

Browser:
Tested and observed on the latest Chrome and Firefox.

**Comment by eCzerniak** [comment]
Thanks for reporting! We will try to fix this as soon as possible.

**Comment by simon-online** [comment]
Thanks, the same thing also happens when filtering by Stock Quantity which requires the Channel filter to also be selected.

<img width="405" alt="Screen Shot 2022-07-07 at 6 18 36 pm" src="https://user-images.githubusercontent.com/10040020/177727213-9f1fe86d-a0f4-49a1-a7e3-f7d5921f351c.png">

**Comment by eCzerniak** [comment]
Ok, I will add this to this one ticket ;) do you have more? :D

**Comment by Droniu** [comment]
New MacawUI release fixes this issue - #2126.

**Comment by simon-online** [comment]
> New MacawUI release fixes this issue - #2126.

When I pull the latest from main and test it this issue is still happening. From what I can see this hasn't been fixed from the new MacawUI release.

Also I'm not able to successfully run a production build of the dashboard with the latest code from main as I get the following errors:
`ERROR in src/apps/components/AppFrame/AppFrame.tsx(41,7):
TS2322: Type '"redirect"' is not assignable to type '"response" | "handshake"'.`

`ERROR in src/apps/components/AppFrame/AppFrame.tsx(43,9):
TS2322: Type '{ path: string; }' is not assignable to type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'.
  Object literal may only specify known properties, and 'path' does not exist in type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'.`

**Comment by simon-online** [comment]
> Actually the Stock Quantity filter doesn't seem to be working on my store after I reload the error screen. It lists all the Available products as Out Of Stock and no products show as Available. I'm not quite sure why that is happening. I haven't been able to reproduce it on the Demo dashboard though.

Note, this particular issue was because I didn't have a shipping zone set up. The rest of this issue is still relevant.

**Comment by simon-online** [comment]
> > New MacawUI release fixes this issue - #2126.
> 
> When I pull the latest from main and test it this issue is still happening. From what I can see this hasn't been fixed from the new MacawUI release.
> 
> Also I'm not able to successfully run a production build of the dashboard with the latest code from main as I get the following errors: `ERROR in src/apps/components/AppFrame/AppFrame.tsx(41,7): TS2322: Type '"redirect"' is not assignable to type '"response" | "handshake"'.`
> 
> `ERROR in src/apps/components/AppFrame/AppFrame.tsx(43,9): TS2322: Type '{ path: string; }' is not assignable to type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'. Object literal may only specify known properties, and 'path' does not exist in type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'.`

Have now resolved this issue by updating dashboard package dependencies before building and can confirm that I'm no longer getting this unexpected error. Thanks
