### ISSUE TITLE
Don't display a price range when only a single product variant

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2147]
In the Price column on the Products screen it shouldn't display a price range when a product only has a single variant. For example Simple products.

It currently displays it as a price range with the same price repeated which just makes it harder to read.

<img width="503" alt="Screen Shot 2022-07-07 at 2 27 47 pm" src="https://user-images.githubusercontent.com/10040020/177691263-9c58fcd5-262e-44bf-827a-1fa2339da0df.png">

**Comment by peelar** [comment]
Hello @simon-online 👋 

Thank you for bringing this up to us. I will pass it to our development team and let you know once it's done.

Have a nice day!
