### ISSUE TITLE
Product Dropdown Select Fields Clicking Arrow Issues

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2155]
On the Create Product screen when I click on the down arrow (in the red circle) of any blank dropdown select field there are a couple of different issues that happen.

<img width="309" alt="Screen Shot 2022-07-07 at 10 32 30 pm" src="https://user-images.githubusercontent.com/10040020/178094651-702a4c8a-a3c9-4c6c-a518-be1bcee2c7ce.png">

Under the Organize Product panel when I click on the down arrow (in the red circle) of any blank dropdown select field (Product Type, Category, Collections) and then click on an option in the dropdown list that appears to select it, the option doesn't actually get selected. The dropdown list just closes like you'd expect but no value is selected. However if I click on another part of the dropdown select (not in the red circle) and then click on an option in the dropdown list that appears then it works as expected.

Under the Attributes section, for any attribute with a dropdown select field when I click on the down arrow (in the red circle) of any blank dropdown select field no options are displayed and it just says "No results found". However if I click on another part of the dropdown select (not in the red circle) then a list of the available options appears and it works as expected.

**System information**

Issues occur on:
Demo Dashboard - dashboard v3.4.1 / core v3.4.10
Latest main branch - dashboard v3.4.0-dev / core v3.5.0-a

Tested and observed on the latest versions of Chrome and Firefox.

**Comment by simon-online** [comment]
This same issue happens with the dropdown select fields under the Settings panel on the Shipping Zone details screen and the Company Information Country field on the Site Settings screen.

**Comment by peelar** [comment]
Hi @simon-online 👋 

Thank you for submitting your issue, you are the best 🥇. 

I managed to reproduce it. I now passed it to our developers and will let you know as soon as it's resolved.

Have a nice day!

**Comment by orzechdev** [comment]
FIxed in https://github.com/saleor/saleor-dashboard/pull/2301
