### ISSUE TITLE
Allow Products screen list to go full width

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2156]
On a large desktop wide screen the main content area is set to have a max width of 1280px which stops it from taking up the full width available. On the Products screen it would be great if there wasn't this restriction so you can configure the products list to display more columns.

It also makes the main nav collapse / expand button not very useful for a large desktop wide screen.

### Describe a proposed solution
Remove the main content area 1280px max width restriction so it can go full width.

![Screen Shot 2022-07-11 at 1 58 12 pm crop](https://user-images.githubusercontent.com/10040020/178186340-000a7a93-1007-4c14-94fc-80c477bddf0e.png)

**Comment by timuric** [comment]
@simon-online I think in your particular example it would not be beneficial to have the table wider, since it will make it less readable. However, when more columns are added, it would be convenient if the table would stretch instead of adding a horizontal scroll.

**Comment by simon-online** [comment]
> @simon-online I think in your particular example it would not be beneficial to have the table wider, since it will make it less readable. However, when more columns are added, it would be convenient if the table would stretch instead of adding a horizontal scroll.

Sure, but in that case a user can decide to resize their browser window to make it smaller but there is currently no way for them to go full width on a large desktop screen when they have additional columns.

**Comment by simon-online** [comment]
It would be great to have this pull request from July reviewed soon
https://github.com/saleor/saleor-dashboard/pull/2166

**Comment by simon-online** [comment]
Keeping this one alive 🤞

**Comment by simon-online** [comment]
Keeping this one alive 🤞

**Comment by timuric** [comment]
@simon-online this view looks quite different in later versions of Saleor, have you seen dashboard 3.13?

**Comment by timuric** [comment]
<img width="1721" alt="image" src="https://github.com/saleor/saleor-dashboard/assets/4006792/8369d4c8-4022-4988-9f2c-dbcdbf15c2a0">

**Comment by simon-online** [comment]
Yeah, I've seen v3.13 of the dashboard. It's definitely an improvement but it still has a max width set.

It's gone from a max width of 1280px to 1920px so on a 27 inch screen it doesn't use the full width as it stops at 1920px.
