### ISSUE TITLE
Filter Products by Availability

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2158]
It would be great to be able to filter products by Availability. This filter would also require the Channel filter to be set.

The Published filter options could be:
Published - filter on Published
Publish In Future - filter on "Publish on" with a future date
Not published - filter on "Not published"

The Availability filter options could be:
Available Now - filter on "Available for purchase"
Available In Future - filter on "Available on" with a future date
Unavailable - filter on "Unavailable for purchase"

The Listed filter options could be:
Listed / Unlisted - filters on "Show in product listings" field

**Comment by peelar** [comment]
Hello @simon-online 👋 

Thank you for your contribution, I am seeing a lot of issues from you lately. That's excellent ⭐, and much appreciated.

There are two things here:
1. The `isPublished` filter
2. The rest of the filters you described

The first one is actually implemented in the API, we just need the UI for it. We created a ticket already.

The second one we need to turn into a https://github.com/saleor/saleor feature request. I published it already and mentioned this issue: https://github.com/saleor/saleor/issues/10370.

We will let you know as soon as both of those are resolved.

Please let us know if you have any questions.

**Comment by simon-online** [comment]
It would be great to keep this moving along now that the additional filters have been added to the core.
https://github.com/saleor/saleor/issues/10370

**Comment by simon-online** [comment]
Keeping this one alive 🤞

**Comment by simon-online** [comment]
Keeping this one alive 🤞

**Comment by gufio** [comment]
Is there any news? I'm especially interested in channel listing isPublished boolean filter.

**Comment by simon-online** [comment]
Keeping this one alive 🤞

**Comment by andrzejewsky** [comment]
Sharing quick update:

Filters are re-implemented on product listing page. I think we still cannot filter everything you have mentioned, but allows to filter by availability.

<img width="642" alt="Screenshot 2023-09-28 at 10 44 22" src="https://github.com/saleor/saleor-dashboard/assets/7943292/2ce8a544-bc86-4de2-903b-eab5cc1f6892">

**Comment by simon-online** [comment]
What version of the dashboard will include this? v3.16.2?

> Sharing quick update:
> 
> Filters are re-implemented on product listing page. I think we still cannot filter everything you have mentioned, but allows to filter by availability.
> 
> <img alt="Screenshot 2023-09-28 at 10 44 22" width="642" src="https://user-images.githubusercontent.com/7943292/271225724-2ce8a544-bc86-4de2-903b-eab5cc1f6892.png">

**Comment by andrzejewsky** [comment]
It's already available since 3.15, but it's under the preview - click on three dots on the left bottom corner (next to account name), open "features preview" then enable product filtering

**Comment by simon-online** [comment]
Oh right, when I enable the new product filtering in dashboard v3.16.1 / core v3.16.2 it works but then it doesn't let me go back and change "Is available" from Yes to No or No to Yes. I have to reset the filters and start again.

Also currently I can't find a way to filter by any of the product attributes fields like you can with the original product filtering.

@andrzejewsky

**Comment by andrzejewsky** [comment]
>  it doesn't let me go back and change "Is available" from Yes to No or No to Yes. I have to reset the filters and start again.
Can't you change the value from "yes" to "no" and opposite? - can do it without any issue?

> Also currently I can't find a way to filter by any of the product attributes fields like you can with the original product filtering.

The left input is autocomplete you can either type attribute name or just scroll down

**Comment by simon-online** [comment]
After I click the Save button and then go back to edit the filters the dropdown sits underneath the pop-up form so I can't click on it. You can see it happening better on the Where dropdown.

> > it doesn't let me go back and change "Is available" from Yes to No or No to Yes. I have to reset the filters and start again.
> 
> Can't you change the value from "yes" to "no" and opposite? - can do it without any issue?
>

**Comment by andrzejewsky** [comment]
Could you share some screenshots or video? that will help us a lot

**Comment by simon-online** [comment]
After I click the Save button and then go back to edit the filters the dropdown sits underneath the pop-up form so I can't click on it.

Notice how the Product type option appears at the bottom because the dropdown is underneath the pop-up form.

![Screen Shot 2023-10-07 at 3 51 52 pm](https://github.com/saleor/saleor-dashboard/assets/10040020/3f50714c-6541-4fef-b0de-2be27d76af87)

dashboard v3.16.1 / core v3.16.2

**Comment by andrzejewsky** [comment]
Hey, ok now I know what you meant, we have fixed that in the latest release 3.17.1
