### ISSUE TITLE
3.5.0 release TypeScript build errors

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor-dashboard#2163]
I'm not able to successfully run a production build of the dashboard from the 3.5.0 release tag or the 3.5 branch as I get the following TypeScript errors:
`ERROR in src/apps/components/AppFrame/AppFrame.tsx`
`ERROR in src/apps/components/AppFrame/AppFrame.tsx(44,7):`
`TS2322: Type '"redirect"' is not assignable to type '"response" | "handshake"'.`

`ERROR in src/apps/components/AppFrame/AppFrame.tsx`
`ERROR in src/apps/components/AppFrame/AppFrame.tsx(46,9):`
`TS2322: Type '{ path: string; }' is not assignable to type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'.
  Object literal may only specify known properties, and 'path' does not exist in type '{ actionId: string; ok: boolean; } | { token: string; version: 1; }'.`

Steps to reproduce:
`git checkout tags/3.5.0`
`npm run build`

The errors also occur on `npm start`.

**Comment by dominik-zeglen** [comment]
Have you tried installing dependencies after checkout?

**Comment by Cloud11PL** [comment]
The "redirect" Event type has been introduced in 0.1.8 version of app-bridge, current version in Dashboard is 0.1.9 https://github.com/saleor/app-bridge/releases/tag/v0.1.9. Try removing `node_modules` and running `npm ci` again. Let me know if it works :)

**Comment by simon-online** [comment]
Yes, that was the problem. Will remember to do this in future with a dashboard update. Thanks for that.

I didn't need to remove `node_modules`. Just running `npm i` was enough.
