### ISSUE TITLE
Support Node 16 LTS

### ISSUE THREAD

**Issue by tiendq** [saleor/saleor-dashboard#2167]
### What I'm trying to achieve

Building dashboard with Node 16 LTS (v16.15.1)

### Describe a proposed solution

Upgrade packages, fix incompatibility issues.

### Other solutions I've tried and won't work

Update `engine` section in `package.json` and try to build under Node v16.15.1 on macOS 11.1 (Big Sur).

### Screenshots or mockups

There are many errors during `npm install` and `npm start`.

**Comment by peelar** [comment]
Hello @tiendq 🖖 

Thank you for paying attention to this issue. We added it to our backlog.

Have a nice day!

**Comment by krzysztofzuraw** [comment]
Current `main` branch support Node 18 (current LTS) - closing
