### ISSUE TITLE
Accessing the next page of swatch attributes values throws an error

### ISSUE THREAD

**Issue by JustCreate3D** [saleor/saleor-dashboard#2205]
### What I'm trying to achieve
I'm trying to click the "next arrow  button" on a swatch attribute value page to acces the next page of values.
### Steps to reproduce the problem

1. Add 10+ values (image or color) to a swatch attribute
2. Either change the number of rows or click on right arrow button to go to the next page

### What I expected to happen
-> Get to the next page of attribute values

### Screenshots and logs

<img width="481" alt="image" src="https://user-images.githubusercontent.com/73743085/181915713-c1f8e00f-c6a7-43d0-af5c-93e34752ae0e.png">
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/73743085/181915834-a063967e-b57c-40a1-bdda-7ff669e5df0d.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/73743085/181915935-73813e5b-2833-4471-8bf8-641ec57a4821.png">

### What I tried
I tried on multiple device/browsers/connections, nothing changed
If I try to change the number of rows to e.g. 100, il will crash again but on the next reload I'll see 100 values. My problem is that I have around 400 values to this swatch and I cannot access to those next values. 
I have multiple other swatch attributes set in the dashboard (some with colors, other with images) and the behaviour is the same for all of them.
Interestingly, on other non-swatch attributes value page I don't have this issue and I can navigate freely between pages of values.

**System information**

Saleor version & dashboard version:
- [x] dev (current main)
We regularly update the dashboard and core to the latest version and it's been hapenning since +/- 3 months, before it was working seemlesly. I haven't noticied the version where it started crashing as I didn't had the necessity to update any value in the dashboard.

Operating system:
- [x] Windows
- [x] Android
- [x] Mac & Iphone

**Comment by peelar** [comment]
Hello @JustCreate3D 👋 

Big thanks for submitting your issue and helping us improve Saleor 🙏.

I managed to reproduce the issue. I now passed it to our developers. I will let you know as soon as it's done.

Have a nice day!
