### ISSUE TITLE
How to change Saleor Logo on the side bar?

### ISSUE THREAD

**Issue by Ivanseven** [saleor/saleor-dashboard#2224]
### What I'm trying to achieve
I'm trying to change the Saleor Logo on the sidebar menu by replacing the files, but it does not change.
It seems like the logo is stored in macaw ui, is there an easy way to change it?
https://github.com/saleor/macaw-ui/blob/362e57d880a46ad5cda039288d5c63864efb39d8/src/Sidebar/Sidebar.tsx#L77

### Steps to reproduce the problem
1. Replacing the files with a different svg:
   - assets\images\logo-sidebar-light.svg
   - assets\images\logo-sidebar-dark.svg

### What I expected to happen
The sidebar logo should change.

### Screenshots

![image](https://user-images.githubusercontent.com/20667826/183374331-fd303b1f-99ce-48fc-b6e2-429aed54ac2e.png)

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by peelar** [comment]
Hello @Ivanseven 👋 

Currently, there is no way to change the logo other than forking the `macaw-ui`. If that ever changes, I will let you know.

**Comment by Ivanseven** [comment]
Thanks @peelar for the response, will close this issue then.
