### ISSUE TITLE
Lots of typescript errors when I run ./node_modules/.bin/webpack-dev-server

### ISSUE THREAD

**Issue by geekysolutionz** [saleor/saleor-dashboard#2262]
### Discussed in https://github.com/saleor/saleor-dashboard/discussions/2261

<div type='discussions-op-text'>

<sup>Originally posted by **geekysolutionz** August 27, 2022</sup>
I am trying to setup a saleor-dashboard instance and trying to link it with my react-storefront.
I get a lot of typescript errors when I run ./node_modules/.bin/webpack-dev-server
Some of the errors are: 
```
ERROR in ./src/warehouses/components/WarehouseList/WarehouseList.tsx:165:24
TS2741: Property 'css' is missing in type '{}' but required in type 'Pick<{ children?: ReactNode; color?: "error" | "action" | "inherit" | "primary" | "secondary" | "disabled"; fontSize?: "small" | "default" | "inherit" | "large"; htmlColor?: string; shapeRendering?: string; titleAccess?: string; viewBox?: string; } & SVGProps<...>, "string" | ... 470 more ... | "css">'.
    163 |                       onClick={stopPropagation(() => onRemove(warehouse.id))}
    164 |                     >
  > 165 |                       <DeleteIcon />
        |                        ^^^^^^^^^^
    166 |                     </IconButton>
    167 |                   </TableButtonWrapper>
    168 |                 </div>

ERROR in ./src/warehouses/components/WarehouseListPage/WarehouseListPage.tsx:62:6
TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & ContainerProps'.
    60 |
    61 |   return (
  > 62 |     <Container>
       |      ^^^^^^^^^
    63 |       <Backlink href={configurationMenuUrl}>
    64 |         <FormattedMessage {...sectionNames.configuration} />
    65 |       </Backlink>

ERROR in ./src/warehouses/index.tsx:23:9
TS2322: Type 'Record<any, string> & Partial<{ asc: boolean; sort: string; }>' is not assignable to type 'WarehouseListUrlQueryParams'.
  Type 'Record<any, string> & Partial<{ asc: boolean; sort: string; }>' is not assignable to type 'Partial<{ asc: boolean; sort: WarehouseListUrlSortField; }>'.
    Types of property 'sort' are incompatible.
      Type 'string' is not assignable to type 'WarehouseListUrlSortField'.
    21 | const WarehouseList: React.FC<RouteComponentProps> = ({ location }) => {
    22 |   const qs = parseQs(location.search.substr(1));
  > 23 |   const params: WarehouseListUrlQueryParams = asSortParams(
       |         ^^^^^^
    24 |     qs,
    25 |     WarehouseListUrlSortField,
    26 |   );

ERROR in ./src/warehouses/index.tsx:24:5
TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'Record<any, string>'.
    22 |   const qs = parseQs(location.search.substr(1));
    23 |   const params: WarehouseListUrlQueryParams = asSortParams(
  > 24 |     qs,
       |     ^^
    25 |     WarehouseListUrlSortField,
    26 |   );

```

All errors are present in this file: 
[all_errors.txt](https://github.com/saleor/saleor-dashboard/files/9436102/all_errors.txt)
Also, as you can see sometimes the webpack-dev-server process gets **KILLED** as well. Need help with that too.
**I seek help from the community, this has really halted my project.**
I am attaching my package.json, webpack.config.js and tsconfig.json files for reference. 

**package.json**
[package.json.txt](https://github.com/saleor/saleor-dashboard/files/9436078/package.json.txt)
**webpack.config.js**
[webpack.config.js.txt](https://github.com/saleor/saleor-dashboard/files/9436083/webpack.config.js.txt)
**tsconfig.json**
[tsconfig.json.txt](https://github.com/saleor/saleor-dashboard/files/9436085/tsconfig.json.txt)

</div>

**Comment by timuric** [comment]
@geekysolutionz could you please elaborate what do you mean by linking storefront with dashboard?

**Comment by timuric** [comment]
@geekysolutionz which release version of dashboard and node runtime are you using?

**Comment by geekysolutionz** [comment]
@timuric 
Node is: v14.20.0
Dashboard is: 3.6.0-dev version
And linking storefront with dashboard means that I want the storefront and dashboard use the same GraphQL API
Anyways, I just mentioned it to convey my end goal but the purpose for this issue and discussion is to resolve the issues when I run the webpack-dev-server.
Also, I also had to change a lot of syntax of the webpack.config.js as the webpack library has been updated but the repo's webpack.config.js file still uses the old version's attributes and tags.

**Comment by timuric** [comment]
Could you please try latest stable release?

**Comment by geekysolutionz** [comment]
Ok

**Comment by geekysolutionz** [comment]
Steps I did

1. git clone https://github.com/mirumee/saleor-dashboard.git
2. git checkout 2.11.1 and got this message: **HEAD is now at 04354fa3e Bump to 2.11.1**
3. npm i
4. npm audit fix --force
5. npm start gives the message: "The command moved into a separate package: @webpack-cli/serve
Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : "
6. And when I try installing it using the above command as well as npm i @webpack-cli/serve --legacy-peer-deps command, I get following errors
`npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /root/codes/backend/test/saleor-dashboard/node_modules/apollo
npm ERR! dest /root/codes/backend/test/saleor-dashboard/node_modules/.apollo-9bOnFpzR
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/root/codes/backend/test/saleor-dashboard/node_modules/apollo' -> '/root/codes/backend/test/saleor-dashboard/node_modules/.apollo-9bOnFpzR'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-28T06_30_21_552Z-debug-0.log`
I am a root user, so doesn't look like a permissions issue. I tried renaming this node_modules/apollo folder, but after that I get a similar error again and this continues.

**Comment by timuric** [comment]
@geekysolutionz latest release version is 3.6.1

**Comment by geekysolutionz** [comment]
@timuric  well then this should change, no?
<img width="880" alt="image" src="https://user-images.githubusercontent.com/112205442/187064835-5a36acba-a9d4-41ee-b9f7-77b736f8244b.png">

**Comment by geekysolutionz** [comment]
@timuric 
I checkout 3.6.1. Downgraded my npm version to 6.11.0 as it was required.
The npm start command asked me to install the @webpack-cli/serve so I installed it and now the 
npm run build-types && webpack-dev-server -d
command stops at the following error
```
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
/root/codes/backend/test/saleor-dashboard/node_modules/webpack-cli/bin/utils/prompt-command.js:46
	return func(...args);
	       ^

TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at runWhenInstalled (/root/codes/backend/test/saleor-dashboard/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
    at promptForInstallation (/root/codes/backend/test/saleor-dashboard/node_modules/webpack-cli/bin/utils/prompt-command.js:140:10)
    at /root/codes/backend/test/saleor-dashboard/node_modules/webpack-cli/bin/cli.js:32:43
    at Object.<anonymous> (/root/codes/backend/test/saleor-dashboard/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)

```

Node version: v14.20.0
Npm version: 6.11.0
package.json:
[package.json.txt](https://github.com/saleor/saleor-dashboard/files/9439614/package.json.txt)

**Comment by geekysolutionz** [comment]
@timuric  ?

**Comment by geekysolutionz** [comment]
I am still facing the issue, I hope anyone can help me out here.
