### ISSUE TITLE
Make better UX in customer column of order table

### ISSUE THREAD

**Issue by rezwan2525** [saleor/saleor-dashboard#2350]
### What I'm trying to achieve
On the order page, if we hover over the `date` cell values of any row, we can see the exact time which is not normally shown on the table. 
The customer column values are compressed as well, not showing the full name. So, won't it be nice if we show the full name when we hover over any customer's name?

### Describe a proposed solution
I think it would be a more consistent and intuitive user experience if we keep similar functionality as `date` column in `customer` column as well. That is **if we hover over `customer` cell values of any row, we should see full name of that customer.**

### Other solutions I've tried and won't work
N/A

### Screenshots or mockups

We can't see full customer name -
![customer_name](https://user-images.githubusercontent.com/30120066/193597175-23d68aac-2812-455c-8057-0dfde6031e38.jpg)

**Comment by peelar** [comment]
Hello @rezwan2525 👋 

The behavior you described is actually only present in the demo mode. In a normal context, we display the full name:
![image](https://user-images.githubusercontent.com/44495184/194853520-8aec5830-ffc9-4b2a-8822-4c0f6e7cef03.png)
