### ISSUE TITLE
Sort products by `created_at` field

### ISSUE THREAD

**Issue by zedzior** [saleor/saleor-dashboard#2363]
### What I'm trying to achieve
I want to sort products by `created_at` field.

### Describe a proposed solution
Suggested API:

```
{
  products(
    first: 5
    sortBy: { field: CREATED_AT, direction: DESC }
  ) {
    edges {
      node {
        id
        name
        created
      }
    }
  }
}
```
Dashboard changes:

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/55899043/194845872-a676c49a-c4a1-4c1c-9410-9192dd1fcbcf.png">

**Comment by lakshya-dhariwal** [comment]
Can i be assigned .Would love to take a stab at it.

**Comment by zedzior** [comment]
> Can i be assigned. Would love to take a stab at it.

Hey Lakshya, it is already under development.
