### ISSUE TITLE
Update templates for issues & pull request and add changelog documentation

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2389]
We need to figure out how we will manage the changelog. 

The result of this task should have the following:
* updates to GitHub templates for issues and PRs (if needed)
* document describing how we manage changelog

**Comment by andrzejewsky** [comment]
let's consider also https://danger.systems/js/ to notify anyone who makes a PR that something is missing, eg. changelog

**Comment by krzysztofzuraw** [comment]
We should explain all possible things you need to do to get CI pass e.g `extract messages`
