### ISSUE TITLE
[Simple Taxes] An error occurs when tax class field is empty.

### ISSUE THREAD

**Issue by eCzerniak** [saleor/saleor-dashboard#2407]
### What I'm trying to achieve
Validation of empty field should not exist.

### Steps to reproduce the problem

1.Go to taxes in configuration
2.Open Countries or Tax classes list.
3.Remove value from some tax rate 
4.Try to save

On Countries list - an error is shown.
On Tax classes - successful notification is shown, but after refresh old value is shown.

### What I expected to happen
It should be possible to leave empty field. Please look at the comment from @Droniu 

### Screenshots
![image](https://user-images.githubusercontent.com/29308910/196647675-82d519f2-eb10-4e27-b24d-0d9e5adf14a1.png)

### System information

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/11042
