### ISSUE TITLE
[Simple taxes] Add Discount -fixed amount - to an order - it is not possible

### ISSUE THREAD

**Issue by eCzerniak** [saleor/saleor-dashboard#2409]
### What I'm trying to achieve

Staff Member cannot add discount with fixed amount to a draftOrder
### Steps to reproduce the problem

1.Create draftOrder 
2.Try to add Discount with fixed amount to whole order 

### What I expected to happen
It should be possible to add discount.
…

### Screenshots
![image](https://user-images.githubusercontent.com/29308910/196672858-b35843f2-4557-43ca-934c-ebfeae2874cf.png)

### System information

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by Droniu** [comment]
That was a backend bug that is already fixed on the feature branch. @maarcingebala can you link a PR which fixed that?
