### ISSUE TITLE
Update dockerfile

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2422]
### What I'm trying to achieve

Our dockers are a bit outdated, we are able to optimize that and are likely to have just one. Additionaly would be nice to have published docker images, ready to consume

### Describe a proposed solution

- Create one production docker file
- use build stages to achieve tiny image (just built code, nothing else)
- create CI action that will publish docker images to ghcr (make it visible [as packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry))
- consider using alpine
- allow the dashboard to switch API URL without rebuilding the image

Refs: https://github.com/saleor/saleor-app-template/issues/95

**Comment by andrzejewsky** [comment]
quick testing, seems like this dockerfile will work fine:

```dockerfile
# 1. dependencies
FROM node:16-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

# 2. build
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn build


# 3. runner
FROM nginx:stable-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/ /app/
```

@orzechdev please have a look

**Comment by tofran** [comment]
@andrzejewsky I would merge the step `1. dependencies` with `2. build` as suggested on #2281
Splitting these seems that it is just creating additional overhead with no gain. Both images are `node:16-alpine` that will be thrown away, so having it in the same build step will allow for cleaner, easier to understand code and possibly slightly faster builds.

**Comment by tofran** [comment]
I am really interesting in this:

> allow the dashboard to switch API URL without rebuilding the image

What the current idea to design this? Is it already discussed somewhere other than #2271?

**Comment by andrzejewsky** [comment]
@tofran so the idea is similar to yours, we also will _sed'ing_ the codebase, but not the js files - just index.html.

We will put our "config" within the window object, which will be initialized in the index.html, now we can _sed_ this based on the variable name. Modifying index.html in the runtime is safer, we don't touch the code itself which is a bit risky.

**Comment by tofran** [comment]
> Modifying index.html in the runtime is safer

Yup I agree, that's much nicer. (Obviously requires code changes that I didn't intend to do initially)

> because thanks to that feature we can end up just with pure nginx image, only with our built codebase.

If you had two stages it would produce the same nginx image, of the same size. Removing one intermediate step.

> ENTRYPOINT ["/entrypoint.sh"]
> Keep the upstream nginx entrypoing

We should not override the upstream entrypoint and should be leveraging `/docker-entrypoint.d/`, otherwise you are removing functionality from the Nginx image.

**Comment by andrzejewsky** [comment]
> We should not override the upstream entrypoint and should be leveraging /docker-entrypoint.d/, otherwise we are removing functionality from the Nginx image.

What do you mean? Because I'm calling the original entry point from Nginx, we keep that.

> If you had two stages it would produce the same nginx image, of the same size. Removing one intermediate step.
hmm as you said in the comments above, yeah I think we can merge deps and build together

**Comment by tofran** [comment]
Hello again @andrzejewsky please see the suggestion in https://github.com/tofran/saleor-dashboard/pull/3

Hopefully we can first merge #2271, and then ship this replacement feature.

**Comment by andrzejewsky** [comment]
@tofran we already did that, it's here: https://github.com/saleor/saleor-dashboard/pull/2473 dockerfiles are also under testing, we basically only need the Github action you created, but I appreciate your quick reaction on this!

**Comment by tofran** [comment]
@andrzejewsky that's awesome. Then we already have all the pieces needed.
Should we merge [the GitHub action](https://github.com/saleor/saleor-dashboard/issues/2271) and [replacement script PR](https://github.com/tofran/saleor-dashboard/pull/3) into [`docker-distribution`](https://github.com/saleor/saleor-dashboard/tree/docker-distribution) branch?

I've already updated [the script](https://github.com/tofran/saleor-dashboard/pull/3/files#diff-a7967fbd5c9cf5edc39fd915c1e58d03741474370407d3f54c363e3f85294368R1-R17) to match what's on https://github.com/saleor/saleor-dashboard/pull/2473.

Are you up to a chat or meet? So we can clear this once and for all? I think we are almost there.
