### ISSUE TITLE
Session in safari doesn't work properly

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2454]
### Steps to reproduce the problem

1. Login by using Safari (I used 15.x version, it still popular one)
2. Refresh the page
3. You lost your session

### What I expected to happen

My session should be kept, even if I refresh the page

### System information

Dashboard version: 3.7.x

Core version:  3.7.x

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [x] Safari 15.x
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
Could not reproduce on newest version - closing
