### ISSUE TITLE
Creating variants error on datagrid

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2470]
Sometimes when we want to save new variants we can face an error that tells us about missing values for the attributes.

### Screenshots
![image (3)](https://user-images.githubusercontent.com/7943292/198027063-c51203be-4bea-409a-af46-7353daecabcc.png)

```
// insert console output here 
```

### System information

Dashboard version: 3.7.x

Core version: 3.7.x

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by Droniu** [comment]
This needs more explicit reproduction steps.

**Comment by krzysztofzuraw** [comment]
How to reproduce:
1. Create a product attribute that is required and is a `Plain text` type
2. Assign product attribute from the previous point to product type
3. Create a product with a newly created product type
4. Create variant of that product and fill product attribute with value
5. Try to save the product details form.
