### ISSUE TITLE
Migrate API_URI to APP_URL

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2502]
We currently use `API_URI` instead of `APP_URL` in `.env.` & CI/CD workflows. After #2473 is merged dashboard code under `src` will use `APP_URL`.

To avoid confusion we should migrate to `APP_URL` in other places:
* `.env`
* CI/CD workflows
* `README.md`
* cypress tests

### Reference
* [The Real Difference Between a URL and a URI](https://danielmiessler.com/study/difference-between-uri-url/#:~:text=google.com%20%E2%80%A6is,to%20get%20there)

**Comment by DylanP97** [comment]
Hi there,
You simply need to replace API_URL by APP_URL in the code ?
