### ISSUE TITLE
Navigating away from "Webhooks & Events" and hitting previous page doesn't redirect to "Webhooks & Events"

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2508]
### What I'm trying to achieve

Go back on dashboard should redirect to previous section in Apps page.

### Steps to reproduce the problem

1. Go to apps in dashboard
2. Navigate to the tab "Webhooks & Events"
3. Click an app from the list
4. Go back (hit the dashboard's "<- Apps" button or previous page browser button)
5. Redirected to the app list instead of "Webhooks & Events"

### What I expected to happen

Navigating away from "Webhooks & Events" and hitting previous page should redirect to "Webhooks & Events".

### Screenshots

https://user-images.githubusercontent.com/9116238/198994398-88da38a5-3439-4efa-a5f2-fc7ac59302b1.mp4

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.9.0-dev`

Core version:

`v3.8.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by Droniu** [comment]
Apps UI has been reworked and Webhooks view is now reachable from configuration view, so this issue is no longer a problem.
