### ISSUE TITLE
Update node to version 18

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2525]
## What needs to be done
* Update to `18.12.0`
* Update `.nvmrc`
* Update GHA workflows to read node version from `.nvmrc`
* Update `setup-node` workflows for GHA to version 3
* Update the docker node version to 18

**Comment by karolm-saleor** [comment]
Task rejected from QA.
This changed caused the Cypress config to fail so now we are not able to run the tests locally
