### ISSUE TITLE
Autocomplete isn't working properly

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2530]
### Steps to reproduce the problem
1. try to use autocomplete on the forms in dashboard

### Screenshots

![autofill](https://user-images.githubusercontent.com/7943292/199946724-1d094b5b-2968-4f9c-a347-5282d1b3fd4c.gif)

NOTE: _Please check the latest version as well_

### System information

Dashboard version: 3.5

Core version: 3.5

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by poulch** [comment]
Can not reproduced, close.
