### ISSUE TITLE
Shipping Rate Pricing can no longer be 0, it has to be 0.01

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor-dashboard#2546]
### What I'm trying to achieve

Trying to activate free shipping rate after a certain treshold, and pricing for it should be 0.
The older versions of the dashboard allowed us to set 0 for the pricing. 

### What I expected to happen

I expected to be able to set pricing to 0. 
As it is now, free shipping costs 0.01 EUR.
…

### Screenshots

![image](https://user-images.githubusercontent.com/75638667/200841953-e93192cb-bb0b-4084-abbb-5e94f2162d6b.png)

### System information

Dashboard version:

`v3.7.9`

Core version:

`v3.7.27`

Operating system:

- Linux

**Comment by kendrice** [comment]
same problem. I want to set up free shipping

**Comment by krzysztofzuraw** [comment]
👋🏻 Thank you for the issue 🥇 

This should be fixed in https://github.com/saleor/saleor-dashboard/releases/tag/3.7.13
