### ISSUE TITLE
Lack of scroll bar in media picker

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2553]
### What I'm trying to achieve

Add media scroll-bar for media picker

### Steps to reproduce the problem

1. Add images for a product until you overflow the picker section

### What I expected to happen

I am supposed to see a scroll bar and be able to navigate over the images

### System information

Dashboard version: 3.8

Core version: 3.8

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
Steps to reproduce the problem are not clear

**Comment by karolm-saleor** [comment]
(/) QA Passed
