### ISSUE TITLE
Improve saving images on the variant editing page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2561]
### Describe a proposed solution
Currently, when we open the modal for picking the media on the variant editing page, each click on the image causes a saving mutation which is not really efficient. Instead, would be nice to add a save button on this modal and once we pick media, by clicking save, we send all of them at once.

### Screenshots or mockups
![Screenshot 2022-11-15 at 13 16 15](https://user-images.githubusercontent.com/7943292/201918497-5e385b17-ee19-41e2-bb8f-a791ed77a1df.png)

**Comment by orzechdev** [comment]
### 2nd proposed solution:
Saving can be performed even after closing a modal, on clicking save button at the bottom page.
