### ISSUE TITLE
Do not bundle testUtils in Docker

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2574]
During #2523 we are copying `testUtils` in order to build the dashboard. We should not do this and remove `testUtils` for creating a production build. After a brief investigation, it seems like the issue is connected with the `fork-ts-checker-webpack-plugin` which is used to type-check webpack build. If it won't be possible to fix this issue we should consider migrating to Vite (#2557)

**Comment by andrzejewsky** [comment]
We can distinguish the following AC here:
- docker should be built without issues and the building process should be faster
- e2e tests are working properly without regressions (including local environment)
- the building works without regressions
