### ISSUE TITLE
Enable "strictNullChecks" in tsconfig

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2584]
Enable rule `strictNullCkecks` in tsconfig. If the rule needs massive changes in the code, please create separate smaller issues to solve it gradually.

- apps #2893
- attributes #2958
- auth
- categories
- channels
- collections
- components
- configuration
- containers
- customers
- discounts
- files
- fragments
- giftCards
- graphql
- home
- hooks
- icons
- marketplace
- navigation
- orders
- pages
- pageTypes
- permissionGroups
- plugins
- products
- productTypes
- searches
- services
- shipping
- siteSettings #2840
- staff
- storybook
- styles
- taxes
- translations #3020 
- utils #2986
- warehouses #2934 
- webhooks #2672

**Comment by Droniu** [comment]
```
npm run check-strict-null-errors | grep "^src/[dirname]"
```

Finds all the files that need to be fixed
