### ISSUE TITLE
Update storybook

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2591]
Update the storybook to the newest version, and remove old dependencies that were required.

**Comment by krzysztofzuraw** [comment]
We can load env variables from the vite config - if we migrate to a storybook with a vite adapter. Thanks to that we will not need to keep env variables in two places:
* `vite.config`
* `storybook.config`

**Comment by andrzejewsky** [comment]
This is needed beforehand: https://github.com/saleor/saleor-dashboard/issues/2891 Also it will simplify the migration (less stories)

**Comment by krzysztofzuraw** [comment]
After update we can move [Decorator](https://github.com/saleor/saleor-dashboard/blob/c60f6f870c85e66499af3c6af53646ea23f35d6b/src/storybook/Decorator.tsx#L15) to [global decorators](https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators).
