### ISSUE TITLE
As an admin I should be able to delete several gift cards on gift card list page

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#2598]
1. Log in via API
2. Create two gift cards via API
3. Enter gift card list page
4. Delete gift cards

Expected reults: 
Get gift cards via API. There is null in response

Link to test cases: https://docs.google.com/spreadsheets/d/1XQ1-babjTVCsKpuDwU91kDt3C-80TJNJ/edit#gid=63822798
Link for all cases with the gift cards: https://app.clickup.com/2549495/v/l/2dtqq-3067
Giftcards instruction: https://docs.saleor.io/docs/3.x/developer/gift-cards

**Comment by karolm-saleor** [comment]
Task done and merged.
https://github.com/saleor/saleor-dashboard/pull/2646
