### ISSUE TITLE
Problems during Save of Product Description

### ISSUE THREAD

**Issue by tilman** [saleor/saleor-dashboard#2599]
### What I'm trying to achieve

Save a product description translation

### Steps to reproduce the problem

1. open a product translation
2. change the translation and save (if we reload page now or look at network request it seems to be saved successfully)
3. return to the translation page, at this point it will ask to discard or save changes again (which does not make sense because it is already saved). If I click safe again it will override the product description with null.

### What I expected to happen

No save dialog again and no override in the description

### Screenshots

https://user-images.githubusercontent.com/5111431/202458643-c9eeb882-918c-4af9-a85e-9a4630ebe5a4.mov

### HTTP request and response from inspector
I can send to you the har file upon request (contains JWT token)

### Console output

```
Navigated to https://saleor-api.pfefferundfrost.de/dashboard/translations/EN/products/UHJvZHVjdDozMA%3D%3D?activeField=description
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/dashboard.0ff54615c6ace0141394.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
A bad HTTP response code (403) was received when fetching the script.
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/8.149cb0831130661a0fd7.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Navigated to https://saleor-api.pfefferundfrost.de/dashboard/translations/EN
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/dashboard.0ff54615c6ace0141394.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
A bad HTTP response code (403) was received when fetching the script.
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/8.149cb0831130661a0fd7.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Navigated to https://saleor-api.pfefferundfrost.de/dashboard/translations/EN/products/UHJvZHVjdDozMA%3D%3D
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/dashboard.0ff54615c6ace0141394.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://saleor-api.pfefferundfrost.de/dashboard/static/8.149cb0831130661a0fd7.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
A bad HTTP response code (403) was received when fetching the script.
```

### System information

Dashboard version:
dashboard v3.7.12

Core version:
core v3.7.35

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
![qa_pass](https://user-images.githubusercontent.com/117726439/205621742-20744beb-abc1-4bc5-a22e-5b2f0de1d010.jpg)
QA Passed

**Comment by karolm-saleor** [comment]
✓ QA Passed
