### ISSUE TITLE
Visual regression on order page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2600]
### Steps to reproduce the problem

1. Go to the order page
2. The tags in payment column have wrong shape (radius) and the input not aligned (screenshots)

### What I expected to happen

…

### Screenshots
expected:
<img width="1505" alt="image (12)" src="https://user-images.githubusercontent.com/7943292/202474196-42a72f29-9b96-4829-826c-6578f0d8ce2c.png">

current:
<img width="1505" alt="image (13)" src="https://user-images.githubusercontent.com/7943292/202474316-92ee178b-927a-4c8e-a85c-588aec364d49.png">

<img width="619" alt="image (14)" src="https://user-images.githubusercontent.com/7943292/202474554-a1e7260c-5eee-4d30-a603-ad2eb7d05d5e.png">

### System information

Dashboard version: 3.8

Core version: 3.8

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
No longer exist
