### ISSUE TITLE
[Fix] should not be able to disable several gift cards on gift card list page and use it in checkout

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#2605]
<google-sheets-html-origin>

Neg | As an admin I should not be able to disable several gift cards on gift card list page and use it in checkout. Before run create product and shipping | 1. Log in via API2. Create gift cards via API3. Enter gift card list page4. Disable gift cards5. Create and complete checkout with gift cards | Error when adding any gift card to checkout. Gift cards amount is not changed | SALEOR_1013
-- | -- | -- | -- | --

**Comment by szczecha** [comment]
Linked issue: https://github.com/saleor/saleor-dashboard/issues/2568

**Comment by michalina-graczyk** [comment]
It is not working on 3.1 , 3.3, 3.4

**Comment by szczecha** [comment]
this test is not included in OldReleases
