### ISSUE TITLE
Fix tests in dataGrid - sku & refactor productVariants tests

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#2607]
products/productsVariants.js
should be able to create variant visible for the customers in all channels. TC: SALEOR_2901 Flaky
<google-sheets-html-origin>

  | Test Scenario: | As an admin I should be able to create variant |   |  
-- | -- | -- | -- | --
  | Test case | Description | Expected Results | Tags
Pos | As an admin I should be able to create variant visible for the customers. Before run create data (category, product type, attribute) for product | 1. Log in via API2. Create new product via API (without variants)3. Enter product details page4. Create single variant4. Enter product details page | Variant with corrrect price should be displayed. Get product info via API and check variant data | SALEOR_2901
Pos | As an admin I should be able to create several variants visible for the customers. Before run create data (category, product type, attribute) for product | 1. Log in via API2. Create new product via API (with variant)3. Enter product details page4. Create variant4. Enter product details page | Variant with corrrect price should be displayed. Get product info via API and check variants data | SALEOR_2902
Pos | As an admin I should be able to create variant in several channels. Before run create data (category, product type, attribute) for product, and channel | 1. Log in via API2. Create new product via API in created and default channel3. Enter product details page4. Create variant4. Enter product details page | Variant with corrrect price should be displayed for both channels. Get product info via API and check variants data for both channels | SALEOR_2903

products/productsWithoutSku/createProductWithoutSku.js    

<google-sheets-html-origin>

  | Test Scenario: | As an admin I should be able to add SKU to product |   |  
-- | -- | -- | -- | --
  | Test case | Description | Expected Results | Tags
Pos | As an admin I should be able to add SKU to simple product | 1. Log in via API2. Create simple product and variant via API3. Enter product details url4. Set SKU | Get variant info via API and check SKU | SALEOR_2802

<google-sheets-html-origin>

  | Test Scenario: | As an admin I should be able to create product without SKU |   |  
-- | -- | -- | -- | --
  | Test case | Description | Expected Results | Tags
Pos | As an admin I should be able create variant without sku by variant creator. Befre run crate data for product | 1. Log in via API2. Create product via API3. Enter product details url4. Create variant without SKU by variant creator5. Create and complete checkout | order is created. Get variant info via API and check SKU. | SALEOR_2806
Pos | As an admin I should be able create variant without sku. Befre run crate data for product | 1. Log in via API2. Create product with variant via API3. Enter product details url4. Create variant without SKU5. Create and complete checkout | order is created. Get variant info via API and check SKU. | SALEOR_2807

**Comment by michalina-graczyk** [comment]
Priority: High

**Comment by szczecha** [comment]
Tests for SKU were fixed in [Fix tests for SKU](https://github.com/saleor/saleor-dashboard/pull/2924)
The main reason for falling  TC: SALEOR_2901 was fixed by changing dashboard behavior [Datagrid - show icon button when single menu item with icon](https://github.com/saleor/saleor-dashboard/pull/2862)
