### ISSUE TITLE
Create missing tests for staff users

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#2608]
As a user I should not be able to create staff member with not unique email - SALEOR_3508
As an staff user I should be able to change my password in account settings - SALEOR_3510
As an admin I want to update staff member - SALEOR_3507
As an admin I should not be able to update staff member with not unique email - SALEOR_3509

https://docs.google.com/spreadsheets/d/1XQ1-babjTVCsKpuDwU91kDt3C-80TJNJ/edit#gid=906353335

**Comment by michalina-graczyk** [comment]
Priority: Medium

**Comment by karolm-saleor** [comment]
Progress so far


![Image](https://user-images.githubusercontent.com/117726439/208892373-a9fe529d-f4b0-47ba-8e87-26620fdc16cc.png)
