### ISSUE TITLE
[FIX]  for tests channelsInDraftOrders.js

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#2614]
It is still not working, need to be fixed. 

<google-sheets-html-origin><style type="text/css"></style>

Pos | As an admin I want to get draft order channel from global channel picker | 1. Log in via API2. Enter home page and check selected channel3. Enters orders list page4. Click create new order button5. Create order without changing channel | Channel should be created in selected channel on home page | SALEOR_2101 | 3.0 and higher
-- | -- | -- | -- | -- | --
Pos | As an admin I should be able to create draft order with channel other than in global channel picker. Before run create channel | 1. Log in via API2. Enter home page and check selected channel3. Enters orders list page4. Click create new order button5. Change channel to created one and submit | Channel should be created in created channel | SALEOR_2102 | 3.0 and higher

https://docs.google.com/spreadsheets/d/1HkmSzHqpILR39HKPTImkPWKK6QZk_xKl/edit#gid=964529466&range=4:5

**Comment by karolm-saleor** [comment]
After investigation I found that this is actually a bug in dashboard
#2913
