### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by anterpin** [saleor/saleor-dashboard#2623]
I just cloned the repo and tried to `npm install`.
It freezes when trying to install @material-ui/icons@4.11.2

**Comment by anterpin** [comment]
- `npm -v`  
8.19.2 
- `node -v`
v16.18.0 
- `uname -a` 
Linux manjaro 5.10.154-1-MANJARO \# 1 SMP PREEMPT Thu Nov 10 20:51:28 UTC 2022 x86_64 GNU/Linux

**Comment by krzysztofzuraw** [comment]
We migrated project to node 18 (current LTS) - can you check if the same problem occurs in Node 18?

**Comment by anterpin** [comment]
Yes, it seems it has fixed the problem.

**Comment by krzysztofzuraw** [comment]
Awesome - I'm closing this issue then. Have a nice day 👋🏻
