### ISSUE TITLE
Modal window "save or discard changes" is missing option to continue to edit

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-dashboard#2633]
Option to continue editing is missing
<img width="665" alt="image" src="https://user-images.githubusercontent.com/4006792/203042774-6e95a2a3-b3a4-4c3c-bfd7-debf402824fd.png">

Suggested UI:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/4006792/203045244-dd2db46c-3e73-4f7b-a7b3-646d5df49b79.png">

Note: Add missing X (close) icon to the modal field

**Comment by karolm-saleor** [comment]
✓ QA Passed
