### ISSUE TITLE
Menu items not disappearing when selecting other menu

### ISSUE THREAD

**Issue by karolm-saleor** [saleor/saleor-dashboard#2639]
### Description
While clicking on the left menu the bars with sub categories are not disappearing while selecting other menu items.
See attached video.

### Steps to reproduce the problem
1. Login to Master Staging Env Dashboard
2. Click on Apps menu
3. Click on Translate menu icon
4. Click on Discounts menu
5. Click on Catalog menu

### Expected Result
Previously selected menu sub-categories should disappear

### Actual Result
Previously selected menu sub-categories are not disappearing and are still active

### System information

Dashboard version:
dashboard v3.9.0-dev

Core version:
core v3.9.0-av

Operating system:
MacOS

Browser:
Chrome

![Screenshot 2022-11-21 at 14 50 39](https://user-images.githubusercontent.com/117726439/203074756-c53d0ed0-421e-4ac2-a546-21863146fcb7.png)

https://user-images.githubusercontent.com/117726439/203074544-bd39b2cc-1423-4fac-af9b-6607046389ef.mov

**Comment by andrzejewsky** [comment]
Thanks for reporting, we are aware of this, and it's already reported here:: https://github.com/saleor/saleor-dashboard/issues/2593
