### ISSUE TITLE
Remove classnames/clsx

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#2651]
We use both classnames and clsx in the dasboard. There's no need for two libraries which solve the same problem.

Recommended solution:
- Try switching to clsx (it's faster & smaller)
- If there are any problems just remove clsx and replace it with classnames

**Comment by lkostrowski** [comment]
`clsx` is used by material, but even if you remove classnames, its still imported with `react-responsive-carousel` (see package lock).

However its still good to unify public usage to single lib
