### ISSUE TITLE
Create a slim/prod Dockerfile

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-dashboard#2664]
### What I'm trying to achieve
I want to introduce a new docker-compose file in [saleor-platform](https://github.com/saleor/saleor-platform)

In this docker-compose I'd like to use only production packages, to play with Saleor locally, not to develop it nor test it.

Currently, Docker setup is very slow because Dashboard is installing e.g. Cypress which is redundant.

In prod/slim package there should be minimal working build.

This docker-compose setup can be useful e.g. for storefront or apps developers who are not changing anything in Saleor, they need only API and Dashboard to set up things

### Describe a proposed solution
...

### Other solutions I've tried and won't work
…

**Comment by andrzejewsky** [comment]
Closed in: https://github.com/saleor/saleor-dashboard/pull/2767 (building time dropped by half)
