### ISSUE TITLE
Restore data-test-id="expand-icon"

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor-dashboard#2720]
### Description of the issue
This Macaw UI update #2512 PR update made a lot of UI changes and we accidentally removed one of the data-test-id `data-test-id="expand-icon"` which now crashes some e2e

Failing spec:
configuration/channels/channels.js
products/menageProducts/availableForPurchaseProducts.js
products/menageProducts/visibleInListingsProducts.js
products/menageProducts/publishedProducts.js

### Screenshots
<img width="737" alt="image" src="https://user-images.githubusercontent.com/30683248/204220210-e06f801a-d626-41b7-befa-f64ac4b757de.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/30683248/204220142-203a61ae-0920-4236-8b6b-89d4a5a77f46.png">

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:
`v3.9.0-dev`

Core version:

`v3.9.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
Related to #2852
