### ISSUE TITLE
Introduce Vitest for testing?

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-dashboard#2740]
### What I'm trying to achieve

I want to run tests productive way

### Describe a proposed solution

Since Vite was introduced, its very easy to replace Jest with Vitest:
- It uses very similar API, so minimal work on migration is required
- Its very fast
- It works with TS out of the box
- Its preconfigured and works out of the box
- It has some APIs jest doesn't that increase productivity

### Other solutions I've tried and won't work

I'm patching jest

**Comment by lkostrowski** [comment]
@andrzejewsky if it happened to be slower than jest, maybe we should just close it? I think it may be good to revisit this in ~6 months to verify progress. I believe vitest provides far better DX due to its APIs, but it may be to early

**Comment by andrzejewsky** [comment]
Yeah just closed the PR with a message, so closing issue as well.
