### ISSUE TITLE
App token is not being copied when clicking "copy" 

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2741]
### Description of the issue
I cannot copy the app token when i click "copy"

### Steps to reproduce the problem

1. Go to apps > Webhooks & Events > Create App
2. Create app
3. Click "copy token"
4. It doesn't copy

### Expected Result
The token should be copied.

### Actual Result
Clicking "copy" does not trigger any resullt.

### System information

Dashboard version: main, work on 3.8.x

Core version: 3.8

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser: Firefox 108.0b7

**Comment by krzysztofzuraw** [comment]
Can't reproduce on `master.staging` with:
* Safari (`16.1`)
* Chrome Mac (`108.0.5359.124`)
* Firefox Mac (`106.0.1`)
