### ISSUE TITLE
Relative dates in dashboard

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor-dashboard#275]
![Screenshot 2019-11-27 at 14 36 43](https://user-images.githubusercontent.com/5188636/69728067-1199ac00-1124-11ea-845d-5bbcd578ed4d.png)

I believe that using relative dates in dashboard application limits it's usage - you have to hover over those to get full date time.

**Comment by maarcingebala** [comment]
I'm looking at the designs and it seems we have absolute dates in a lot of list views. @pwgryglak Should we use absolute dates everywhere or are there any exemptions when relative dates are recommended?
