### ISSUE TITLE
Paginate tax rates in the tax class view

### ISSUE THREAD

**Issue by orzechdev** [saleor/saleor-dashboard#2756]
### What I'm trying to achieve
The list of tax rates on the tax class view is way too long. It should be paginated.

### Describe a proposed solution
The list of tax rates on the tax class view should be paginated.

### Acceptance Criteria 

The list of tax rates on the tax class view should be paginated.

### Screenshots or mockups

<img width="1466" alt="Screenshot 2022-11-30 at 14 38 02" src="https://user-images.githubusercontent.com/9825562/204811123-db48d82b-2b44-48a6-91eb-215337d5c20c.png">

**Comment by michalina-graczyk** [comment]
QA approved
