### ISSUE TITLE
Sidebar menu overload

### ISSUE THREAD

**Issue by endo-aki22** [saleor/saleor-dashboard#2761]
### Description of the issue
Sidebar menu overload
…

### Steps to reproduce the problem

1. click a sidebar menu that has submenus to see popover.
2. without clicking submenu, click another sidebar menu that has submenus also.
3. And then the two popover is overloaded each other.

### Screenshots

![11-30-22-10-44-23](https://user-images.githubusercontent.com/61251512/204873139-17c5056d-4375-4fe9-8482-b7943abcf9ed.png)

**Comment by krzysztofzuraw** [comment]
Hi @endo-aki22 and thank you for the issue 👋🏻 

We already have this issue in our backlog https://github.com/saleor/macaw-ui/issues/177
