### ISSUE TITLE
[ CORS ] => Having cors problem for the admin dashboard

### ISSUE THREAD

**Issue by dharmendrasha** [saleor/saleor-dashboard#2771]
### Description of the issue
Cannot login due to the cors issue.
…

### Steps to reproduce the problem

1. Install saleor and update the env with prod endpoints
2. update the nginx as well 
```
location / {            
            add_header 'Access-Control-Allow-Origin' '*' always;
            proxy_pass http://localhost:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            include     /home/ashish/Downloads/projects/saleor/core-api/uwsgi_params;
            include /etc/nginx/snippets/cors.conf;
            include /etc/nginx/snippets/cors-wildcard.conf;
    }

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { access_log off; log_not_found off; }
    location ~ /\. { deny  all; access_log off; log_not_found off; }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.dingpack.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.dingpack.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

    
server {
    if ($host = api.dingpack.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
```
# container endpoints
```
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=https://react-storefront.dingpack.com/
      - DASHBOARD_URL=https://admin.dingpack.com/
      - ALLOWED_HOSTS=api.dingpack.com,localhost,api,140.238.230.137,admin.dingpack.com,react-app-checkout.dingpack.com,react-app-checkout.dingpack.com
      - ALLOWED_CLIENT_HOSTS=admin.dingpack.com,react-storefront.dingpack.com,react-app-checkout.dingpack.com,api.dingpack.com,localhost
      - ALLOWED_GRAPHQL_ORIGINS=admin.dingpack.com,react-storefront.dingpack.com,react-app-checkout.dingpack.com,api.dingpack.com,localhost
```

cors is working for graphql and storefront but not for admin dashboard

### Expected Result
should not have any cors related issue?

## cors issue with admin
<img width="580" alt="image" src="https://user-images.githubusercontent.com/62466056/205213030-46c992e5-98f5-49aa-a3de-48ed707410af.png">

## not having cors issue with storefront
<img width="504" alt="image" src="https://user-images.githubusercontent.com/62466056/205213080-7c9eb512-9419-4cf0-a9cb-7b89364e3863.png">

### System information

Dashboard version:

`v3.8.5`

Core version:

`v3.8.5`

Operating system:

- [x] Windows
- [x] Linux
- [x] MacOS

Browser:

- [x] Safari
- [x] Chrome

**Comment by dharmendrasha** [comment]
If i can disable cors globally it would be great!

**Comment by patrys** [comment]
In Saleor, CORS is controlled by `ALLOWED_GRAPHQL_ORIGINS`. Ensure your reverse proxy (i.e., Nginx) does not change the response and forwards the `origin` header correctly.

**Comment by patrys** [comment]
By the way, it supports glob expressions so you can also set `ALLOWED_GRAPHQL_ORIGINS` to values like `*.foo.com`.
