### ISSUE TITLE
Add image to product picker

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-dashboard#2775]
In some cases when product names are not unique users can not distinguish products
![image](https://user-images.githubusercontent.com/4006792/205286555-777a507c-8cce-4aca-a530-23ef5d0ab148.png)

AC:
- [ ] Each image on the list in the modal should have image

**Comment by krzysztofzuraw** [comment]
I'm closing it as it was affecting the dashboard till the https://github.com/saleor/saleor-dashboard/releases/tag/3.8.0 version.
