### ISSUE TITLE
[Fix] should be able to create variant

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-dashboard#2781]
It looks like this test is trying to create products that already exist.

Version: Check all versions.

After merging to 3.7 close issues:
 - https://github.com/saleor/saleor-dashboard/issues/2748

**Comment by szczecha** [comment]
Close after https://github.com/saleor/saleor-dashboard/issues/2607

**Comment by szczecha** [comment]
In 3.9 and higher this test was fixed by changing the dashboard behavior https://github.com/saleor/saleor-dashboard/pull/2862
