### ISSUE TITLE
[Fix] Tests for Pages

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-dashboard#2782]
Versions: >= 3.7

Issues to close after merging:
- https://github.com/saleor/saleor-dashboard/issues/2747
- https://github.com/saleor/saleor-dashboard/issues/2717
- https://github.com/saleor/saleor-dashboard/issues/2716
- https://github.com/saleor/saleor-dashboard/issues/2715

**Comment by szczecha** [comment]
Investigate why those tests are failing and fix
Priority: Medium

**Comment by karolm-saleor** [comment]
#2948
