### ISSUE TITLE
Service worker is being reloade in the loop

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2786]
### Description of the issue
When we run production mode, the service worker is reloaded in the loop, which causes multiple calls for sw.js. It happens because SW_INTERVAL has no default value, thus setInteval (in useServiceWorker) triggers its callback instantly

### Steps to reproduce the problem

prep: clean service worker in the browser
1. Build the app
2. Run it (sw.js is loaded for the first time) (go to the build/dashbaord and run `npx http-server . -p 4173`)
3. Build the app again
4. go to the build/dashbaord and run `npx http-server . -p 4173`
5. You can notice in the server console multiple calls for `sw.js`

### Expected Result
Infinite requests for sw.js

### Actual Result
Request for sw.js trigger periodically

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
✓ QA Passed
