### ISSUE TITLE
Set the proper open-graph properties 

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2823]
### What I'm trying to achieve
Currently, we don't have any open graph meta tags so when we share the link to the dashboard it does not look good.

### Describe a proposed solution
Please add open-graph tags, we can use https://www.opengraph.xyz/ as a validator

### Acceptance Criteria 
- [x] Dashboard passes the test on https://www.opengraph.xyz/ validator

**Comment by karolm-saleor** [comment]
✓ QA Passed
