### ISSUE TITLE
No docker package release for 3.9.0+ releases.

### ISSUE THREAD

**Issue by pitkes22** [saleor/saleor-dashboard#2828]
I am trying to install the latest version of the dashboard using docker but there is no docker image for the 3.9.0 and 3.9.1 versions published.

**Comment by krzysztofzuraw** [comment]
Hi @pitkes22 and thank you for creating the issue and letting us know 👋🏻

We already have #2767 which fixes the issue. This change needs to be cherry-picked to the `3.9` branch. I will ping you here when we have it fixed 😄

**Comment by krzysztofzuraw** [comment]
@pitkes22 should be fixed now: https://github.com/saleor/saleor-dashboard/pkgs/container/saleor-dashboard/58013736?tag=3.9.2 😄
