### ISSUE TITLE
Migrate from fuzzaldrin

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2837]
### What I'm trying to achieve
Since `fuzzaldrin` is very old library with no maintenance, would be nice to migrate it to https://fusejs.io/.

### Acceptance Criteria 
- [ ] Removed `fuzzaldrin`
- [ ] fuzzaldrin replaced by fuse.js
- [ ] fuzzy search works

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work
