### ISSUE TITLE
Staff Member Information are not saved

### ISSUE THREAD

**Issue by ashishkpaul** [saleor/saleor-dashboard#2847]
### Description of the issue
same as title
…

### Steps to reproduce the problem

1. click on "account settings" right upper corner of the user profile
2. Update the first name and last name then click on save

### Expected Result
It shoul be save
…

### Actual Result
Not saving
…

### Screenshots

![Screenshot_2022-12-13_09-39-39](https://user-images.githubusercontent.com/16308863/207224461-638536e9-0b30-4f0b-a200-7365fb16e501.png)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:
3.9.4
`v?.?.?` (e.g. `v3.6.0`)

Core version:
3.9.3
`v?.?.?`

Operating system:

- [ ] Windows
- [* ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [* ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
Error message:

(uncaught exception)TypeError: Cannot read properties of undefined (reading 'permissionGroups')
5

**Comment by andrzejewsky** [comment]
related: https://github.com/saleor/saleor/issues/11691

**Comment by ashishkpaul** [comment]
Hello i upgraded the coreapi and dashboard to 3.10.0 and facting the same results

**Comment by andrzejewsky** [comment]
We need to use here a different mutation for saving user's own data when he is visiting his profile. Atm we use staff-related mutations which are meant to be used as admin.
