### ISSUE TITLE
Datagrid is missing cell borders on Safari desktop

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2870]
### Description of the issue

Datagrid is missing cell borders on the Safari desktop.

### Steps to reproduce the problem

1. Go to the product detail page
2. Scroll down to datagrid

### Expected Result

Datagrid is displayed with cell borders.

### Actual Result

Datagrid is displayed without cell borders.

### Screenshots

![CleanShot 2022-12-16 at 12 36 36@2x](https://user-images.githubusercontent.com/9116238/208106148-c7f160b7-5ec9-4774-b1f8-f8a27849799a.jpg)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.10-dev`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [x] Safari (16.1)
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
No longer exists on newer versions. Closing
