### ISSUE TITLE
Default value STATIC_URL

### ISSUE THREAD

**Issue by BBrowns** [saleor/saleor-dashboard#2875]
Currently, the default value `STATIC_URL` in the saleor-platform/saleor-dashboard/Dockerfile is set to `/dashboard/`. However, in the `README` it states: 

"`STATIC_URL` - URL where the static files are located. E.g., if you use an S3 bucket, you should set it to the bucket's URL. By default, Saleor assumes you serve static files from the root of your site at "http://localhost:9000/".". 

This suggests that the default value should be http://localhost:9000/. 

Furthermore, in saleor-platform/saleor-dashboard/Dockerfile.dev the default value of `STATIC_URL` is set to `/`. 

Currently, I'm trying to enable remote acces to Saleor-platform using nginx and these default values seem contradicting.

**Comment by krzysztofzuraw** [comment]
Hi @BBrowns and thank you for creating the issue 👋🏻

About the default value of `STATIC_URL` - as we run the dashboard at `localhost:9000` (in developer mode) it means that `STATIC_URL` should be `/` as the browser will interpret that static files are available at `localhost:9000`. We allow you to change that to your liking for production mode. Maybe this picture will give you more clarity:

![image](https://user-images.githubusercontent.com/9116238/208373088-0d91b430-0d53-4e21-b6f1-b8a454d88768.png)


About `Dockefile.dev`. Can you check the latest version of https://github.com/saleor/saleor-platform? We removed `Dockerfile.dev` in the dashboard a couple of weeks ago - there should be only one `Dockerfile`.
