### ISSUE TITLE
Reference attribute search bar doesn't work

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#2877]
### Description of the issue

When trying to search through products/variants while adding reference attribute, modal hides and state is broken.

### Steps to reproduce the problem

1. Go to product details view which has reference attribute
2. Assign reference
3. Type anything in search

### Expected Result
Search works

### Actual Result
Modal breaks

### Screenshots
<img width="586" alt="image" src="https://user-images.githubusercontent.com/41952692/208129881-f88f4008-7523-4fb0-92ab-b536ddb304b2.png">

### Console output
No error

### System information

Dashboard version:

`v3.10.0-dev`

Core version:

`v3.10.0-dev`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
✓ QA Passed
