### ISSUE TITLE
No default channel preselected in new Order creation

### ISSUE THREAD

**Issue by karolm-saleor** [saleor/saleor-dashboard#2913]
When user is entering Orders and creating a new one then there is no default channel selected.
Default selected channel should be visible

Steps to reproduce:
1. Login to dashboard
2. Notice what default channel is selected in the upper right corner
3. Go into new Order creation (Orders->Create order)

Expected Result:
Default channel is preselected

Actual Result:
No channel is preselcted

### Screenshots
![image](https://user-images.githubusercontent.com/117726439/209310268-3609d803-76e5-4ee0-aa80-057bfd4f55c9.png)

dashboard v3.10.0-dev
core v3.10.0-a

chrome 108 @ macOS 13.0.1

**Comment by wojteknowacki** [comment]
It no longer exists. Closing
