### ISSUE TITLE
Staff member cannot access the account settings page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2966]
### Steps to reproduce the problem

1. Create staff member without permissions
2. Login by using this account
3. Open account settings

### Expected Result
I should see my account along with my settings, and can change the password

### Actual Result
404 error page

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolm-saleor** [comment]
✓ QA Passed
