### ISSUE TITLE
Error during sending invoice 

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2972]
Related: https://github.com/saleor/saleor-app-invoices/issues/1

### Steps to reproduce the problem

1.Install saleor app invoice in Apps
2. Go to orders
3. Select random order -> https://master.staging.saleor.cloud/dashboard/orders/T3JkZXI6MTg0NDE0NjktNTYyYy00Njc1LTg2ZWYtMDc4NTY3NGM1ZThj
4. Click 'generate invoice'
5. Select Invoice Invoice 1/5/2023
6. Click send

### Expected Result
I should send the invoice

### Actual Result
error (screenshot below)

### Screenshots
<img width="1916" alt="211545313-d9a60596-0719-411e-9baa-548b05698210" src="https://user-images.githubusercontent.com/7943292/211755015-e1581a13-ca6f-4682-ac5e-4b4a12a153fd.png">

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by michalina-graczyk** [comment]
![image](https://user-images.githubusercontent.com/25908728/213691326-9b1d7afd-c1a2-419e-b97d-a71ad3f14d10.png)
works correctly now
