### ISSUE TITLE
Avoid calculating money on the frontend

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-dashboard#2974]
### Description of the issue

Saleor API returns total order line value (price * quantity)

```graphql
{
  order{
    lines{
      totalPrice{
        gross{
          amount
        }
      }
    }
  }
}
```

In `src/orders/components/OrderProductsCardElements/OrderProductsTableRow.tsx` amount is calculated incorrectly, on frontend, causing precision problems `line.quantity * line.orderLine.unitPrice.gross.amount`

### Steps to reproduce the problem

1. Compare `lines.totalPrice` with result from API. Some products will have invalid calculations

[See this comment](https://github.com/saleor/saleor-app-invoices/issues/1#issuecomment-1377164102)

### Expected Result

All calculations are performed on the backend; frontend is displaying the value without calculations 

### Actual Result

Frontend calculates values, sometimes causing invalid results

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by szczecha** [comment]
@andrzejewsky @lkostrowski isn't it the same issue https://github.com/saleor/saleor-dashboard/issues/2963?

**Comment by lkostrowski** [comment]
> @andrzejewsky @lkostrowski isn't it the same issue #2963?

Yes, closing as a duplicate
