### ISSUE TITLE
404 after deleting app

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor-dashboard#2987]
### Description of the issue
404 after deleting app

### Steps to reproduce the problem

1. Install app
2. Open app settings
3. Delete app

### Expected Result
Redirect to /apps/

### Actual Result
Dashboard stays at /apps/appID/ and display 404 error

### Screenshots

https://user-images.githubusercontent.com/30683248/212347092-44b4efc5-3057-4cb4-b4a2-a9fadabc9628.mov

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:
`v3.11.0-dev`

Core version:
`v3.10.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
Not existing on latest versions
