### ISSUE TITLE
Update cypress version in dashboard e2e

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor-dashboard#2989]
Current version 10.0.2

Update to 12.X

**Comment by karolm-saleor** [comment]
After changing Cypress to 12.3 in package json there are over 140 failing tests
https://cloud.cypress.io/projects/51ef7c/runs/2526/overview

**Comment by karolm-saleor** [comment]
As for now 198 tests are passing, 39 are failing.
Most of the fails is due to mutations.
@szczecha has a solution for that that needs to be discussed.

**Comment by karolm-saleor** [comment]
Investigation about mutations not working, might be an innues with aliases:

https://github.com/cypress-io/cypress/issues/25448
https://github.com/cypress-io/cypress/issues/25210
