### ISSUE TITLE
Prettier formatting is run neither on commit nor on CI

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#2996]
### Description of the issue
Prettier is supposed to run together with ESLint, but it is not. Formatting is not checked.

### Steps to reproduce the problem

1. Run `npx prettier --check "src/**/*.@(tsx|ts|jsx|js)"`
2. Open any PR - lint should fail becuase of the prettier error

### Expected Result
There should no problems or lint check on CI should fail

### Actual Result
There are problems detected by prettier which are not fixed by `npm run lint` and CI checks pass.

### Console output
```
npx prettier --check "src/**/*.@(tsx|ts|jsx|js)"
Checking formatting...
src/taxes/components/TaxCountryDialog/styles.ts
Code style issues found in the above file(s). Forgot to run Prettier?
```

### System information

Dashboard version:

`v3.11.0-dev`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by wojteknowacki** [comment]
Already fixed
