### ISSUE TITLE
Re-shape layout

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#2999]
### What I'm trying to achieve
Currently, the dashboard has a layout that is separated by the spacings, without any structure. Since we are going to use new designs as well as macaw-ui, would be nice re-shape that layout and define it properly

### Describe a proposed solution
Let's use `Box` component to recreate layout, that is divited into sections of: left sidebar, right sidebar, top nav, main content. Please use macaw-ui schema colors as well as spacings to define the appearance of it

### Acceptance Criteria 
- [ ] Defined layout by created dedicated components for each section (by using Box)
- [ ] Colors and the other primitives are taken from macaw-ui (next)
- [ ] Theme can be reactive (we can change theme when we apply new token)

### Screenshots or mockups
![Screenshot 2023-01-18 at 10 21 49](https://user-images.githubusercontent.com/7943292/213133068-58b42a1b-d309-4a93-a613-e6cc21ced26b.png)

**Comment by michalina-graczyk** [comment]
The curson is behind the text 
Device: Windows
Browser: Chrome 
Link: https://watch.screencastify.com/v/UqdBiOHEAk9YQTAgeFF1

**Comment by michalina-graczyk** [comment]
Sidebar is not hiding when I select eg. gift cards
Device: Iphone 13 mini
Steps:
1. Open left bar
2. Expand the catalog -> gift cards
Current result: Sidebar is not dissapearing 
Expected result: After click on selected item, sidebar is hiding and user can see the app

![Image](https://user-images.githubusercontent.com/25908728/219393291-c10a54c7-8352-4038-806c-3611e7713c5c.png)

**Comment by szczecha** [comment]
It would be better if warehouses and shipping zones have left/right padding 
![image](https://user-images.githubusercontent.com/30683248/219392881-a01f03d2-8fa7-4d23-8bd3-79a32c244ba1.png)

**Comment by szczecha** [comment]
Position of configuration Save button on the shipping methods page should align with the unit dropdown

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/30683248/219394745-75e94c4b-fef4-4ed0-8a81-594c64204772.png">

**Comment by michalina-graczyk** [comment]
The font size is too small in "issue gift card create"
Steps:
1.Go to catalog->Gift Cards
2. Click "issue card" button

![Image](https://user-images.githubusercontent.com/25908728/219395500-85630858-5b31-4485-8621-16f5c5f91c6b.png)

**Comment by wojteknowacki** [comment]
Animation error when unfolding the availability list of the product details page.

Mac os Ventura 13.0.1
Chrome  109.0.5414.119

Steps:

1. Go to the product detail view
2. Click manage availability
3. Add channel
4. Expand just added channel description



https://user-images.githubusercontent.com/124166231/219399113-a33a2796-0825-46dc-9437-4e61f7f5868c.mov

**Comment by wojteknowacki** [comment]
The right section on product details jumps when expanding Metadata fields

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Go to the product detail view
2. Scroll the center section to the bottom
3. Add private metadata
4. Fold private metadata 
5. Unflod it

Expected result:
- Right section stays still

Actual result: 


https://user-images.githubusercontent.com/124166231/219403533-397f4595-5a97-4bb3-b767-d7a5b5a0bb88.mov

**Comment by wojteknowacki** [comment]
Searching products triggers the whole table UI reload.

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Go to the product list view
2. Type "a"
3. Type "b"

Expected result:
Similar to stage env - only row reload when searching

Actual result:


https://user-images.githubusercontent.com/124166231/219406813-acaf0f7d-cc31-4978-8789-da2bc849267b.mov

**Comment by wojteknowacki** [comment]
UI reloads when the user changes the sorting.

Mac os Ventura 13.0.1
Chrome 109.0.5414.119


You can trigger it in different ways:

1. Go to the product list view
2. Change sorting by clicking on the table column title

If this does not work try:

1. 1. Go to the product list view
2. Change sorting by clicking on the table column title
3. Add filter
4. Change sorting by clicking on the table column title

Expected result:
The table does not change shape just reloads sorted products

Actual result:


https://user-images.githubusercontent.com/124166231/219408978-94867fd3-0952-4e55-a911-171237e98e48.mov

**Comment by szczecha** [comment]
Switch animation, the circle has a visible shadow

Browser Safari, Chrome 
macOS Ventura 13.1

https://user-images.githubusercontent.com/30683248/219580817-2907be33-bbd0-4d64-a7e7-afaed63ce15c.mov

**Comment by wojteknowacki** [comment]
Date picker issues

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Go to the product list
2. Open Filters
3. Pick filter option with date picker
4. open date picker
5. scroll date picker view

Expected result:
- scroll disabled
or
- displayed month adjusted to scroll value

Actual result: 
- scroll value not visible with displayed month/year in the date picker left top corner

https://user-images.githubusercontent.com/124166231/219584198-e04d469f-ee38-415c-8d74-0bbeb0e8d0d3.mov

**Comment by wojteknowacki** [comment]
Product details view scrolling

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

- Open product details view
- Make sure the right section height is scrollable by adding extra fields
- Scroll the central section to the bottom

Expected result:
Scrolling the central section doesn't scroll right section

Actual result:
Reaching the bottom of the central section triggers right section scroll

https://user-images.githubusercontent.com/124166231/219585949-3d6b7e69-3010-4246-b30b-9972435dc8ec.mov

**Comment by wojteknowacki** [comment]
The list view tooltip misplaced

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Go to the product list view
2. Hover the price column title

Expected result:
Tooltip placed above the column name

Actual result:
Tooltip in misplaced

![Image](https://user-images.githubusercontent.com/124166231/219587888-89f12682-906f-48ec-9596-e4a5078e5c29.png)

**Comment by szczecha** [comment]
Missing styling for the General Settings label

Browser Safari
macOS Ventura 13.1

![image](https://user-images.githubusercontent.com/30683248/219592935-77105a84-c860-415f-81bc-89c207a1c4a2.png)

**Comment by michalina-graczyk** [comment]
Device: iphone 12 Pro
1. Go to order -> drafts -> order details

![Image](https://user-images.githubusercontent.com/25908728/219593369-0f8d76f7-3b5b-4ec9-a47e-271c21f0ca83.png)

**Comment by szczecha** [comment]
Styling of the message: order cannot be placed in an inactive channel 

Browser Safari
macOS Ventura 13.1

https://user-images.githubusercontent.com/30683248/219594701-eb8258e6-384d-4323-86dd-8d9d7e9f4c8a.mov

**Comment by michalina-graczyk** [comment]
Apps on mobile view

![Image](https://user-images.githubusercontent.com/25908728/219596297-d1c060d6-451f-445c-94c9-4836efa803ab.png)

**Comment by wojteknowacki** [comment]
Search engine preview 

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Open product details view
2. Click Edit website SEO
3. Start typing in Slug input
4. Start typing in the engine title input
5.  Start typing in the engine description text field


Expected result:
The character number validator is placed on the right edge of the input

Actual result:

![Image](https://user-images.githubusercontent.com/124166231/219596889-c8b03a74-183f-4311-bbe1-bead82b2f27d.png)

**Comment by wojteknowacki** [comment]
Details view right section empty space

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Open product details view
2. Scroll right section to the bottom

Expected result:
No extra free space

Actual result:

![Image](https://user-images.githubusercontent.com/124166231/219598545-4e0384c8-b584-4d5c-af19-5af68e242f28.png)

**Comment by michalina-graczyk** [comment]
Configuration-menu-attributes 

![Image](https://user-images.githubusercontent.com/25908728/219598654-837a3a52-fc35-4183-9d9c-78da2dd6d5ac.jpeg)

**Comment by michalina-graczyk** [comment]
1. Go to discount -> vouchers 
2. Set some value in channel 
3. scroll down
Result: Discount Vaue is visible on the footer

https://user-images.githubusercontent.com/25908728/219603730-d59102df-adf7-463d-b516-78f5a256ea8a.webm

**Comment by wojteknowacki** [comment]
Search filter - extra spacing

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Go to the product list view
2. Open filters
3. Pick AttrCreate17205

Expected result:
No extra spacing

Actual result:


![Image](https://user-images.githubusercontent.com/124166231/219639961-79d32942-6bf8-43ca-88d9-2642baad306e.png)

**Comment by wojteknowacki** [comment]
Main page layout 

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

XL resolution

1. Go to the Main page

Expected result:


![Image](https://user-images.githubusercontent.com/124166231/219641076-a25ddd7e-b5ce-4d7d-9ca7-b5ae6dc9a616.png)



Actual result:

![Image](https://user-images.githubusercontent.com/124166231/219640728-1bc70b12-eb54-4f83-9238-22562faad972.png)

**Comment by wojteknowacki** [comment]
Dark theme issue - description edition button not visible

Mac os Ventura 13.0.1
Chrome 109.0.5414.119

1. Start creating a new product
2. Add a description - a few paragraphs

Expected result:
Edition buttons are visible when hovering the description text field

Actual:
The description dot button is not white when text field hovered

https://user-images.githubusercontent.com/124166231/219643147-49e99ba6-0106-4d23-b00a-cd592824ee86.mov

**Comment by szczecha** [comment]
Is it expected to change the height of the Install app button button 

Browser Safari
macOS Ventura 13.1\
<img width="233" alt="Screenshot 2023-02-17 at 13 38 35" src="https://user-images.githubusercontent.com/30683248/219655722-57be698c-bb9e-4eed-8654-4d6ce621ca86.png">
<img width="365" alt="Screenshot 2023-02-17 at 13 34 46" src="https://user-images.githubusercontent.com/30683248/219655734-a86873d0-3c4a-41af-ab36-53640d5a9129.png">

**Comment by szczecha** [comment]
On the install app, page buttons are glued to line

Browser Safari
macOS Ventura 13.1

<img width="1526" alt="Screenshot 2023-02-17 at 13 35 04" src="https://user-images.githubusercontent.com/30683248/219655965-faa6d82a-24f5-47c7-bbf4-7dc4eead46c5.png">
