### ISSUE TITLE
Dashbaord crashes when user try to change something in its detail page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3033]
### Steps to reproduce the problem

1. Account settings 
2. Try to change an email (especially as user with strict permission)
3. Dashboard crashes

### Expected Result
Since you can't right now change an email (https://github.com/saleor/saleor/issues/11691) dashboard should at least show an error notification

### Actual Result
Dashboard crashes

### Console output

```
Uncaught (in promise) TypeError: can't access property "permissionGroups", user2 is undefined
    groupsDiff 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karola312** [comment]
QA approved
