### ISSUE TITLE
Fix 6 flaky failing e2e tests

### ISSUE THREAD

**Issue by karolm-saleor** [saleor/saleor-dashboard#3075]
Failing tests:
https://cloud.cypress.io/projects/51ef7c/runs/2784/overview?reviewViewBy=FAILED&utm_source=slack

**Comment by karolm-saleor** [comment]
Test are passing locally.
Additionally when the whole test suit was run today they also passed:
https://cloud.cypress.io/projects/51ef7c/runs/2811/test-results

**Comment by szczecha** [comment]
These tests failed on [New macaw reshaping ](https://github.com/saleor/saleor-dashboard/pull/3069) branch.
