### ISSUE TITLE
Draftail formatting options

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-dashboard#31]
![image](https://user-images.githubusercontent.com/5421321/53746265-1dac5200-3ea1-11e9-9037-41e3720967c2.png)

List of formatting options in our editor is now very basic and I think we could extend it a little bit to support a few other common options. Here is my proposition:

- P, H1, H2, blockquote
- bold, italic, underline, strikethrough
- ul, ol
- alignment
- link, image
- clear formatting

From those that we have now I would only remove the one that inserts a new line.

**Comment by JannikZed** [comment]
Hey guys, I would like to assist on the image implementation. We most likely need the draft-js-plugin https://www.draft-js-plugins.com/plugin/image right? We want to use our saleor instance as the main CMS also for several seo-relevant sub-pages, so this feature is important to us.

**Comment by maarcingebala** [comment]
CC @dominik-zeglen / @benekex2.
