### ISSUE TITLE
Order history do not show full timestamps on date hover

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3115]
### Description of the issue

Order history does not show full timestamps on the date hover inside order detail -> order history.

### Steps to reproduce the problem

1. Go to order detail
2. Scroll down to order history
3. Hover over the timestamp

### Expected Result

The full date displayed on the tooltip is shown to the user.

### Actual Result

Nothing happens

### Screenshots

Before
---
![CleanShot 2023-02-06 at 16 43 10@2x](https://user-images.githubusercontent.com/9116238/217016764-257b453d-d37c-40b7-889b-85d492b76be7.jpg)
After
---
![CleanShot 2023-02-06 at 16 43 28@2x](https://user-images.githubusercontent.com/9116238/217016859-1aa6151b-3c6a-4262-ab3d-1bd115596657.jpg)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.10.x`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by timuric** [comment]
Also timestamps in orders table and order view
<img width="519" alt="image" src="https://user-images.githubusercontent.com/4006792/217017636-b4302b7c-e496-496e-aa24-de38d7d4d12a.png">


<img width="392" alt="image" src="https://user-images.githubusercontent.com/4006792/217017681-3ff88690-aa4e-4427-a8d2-82e065c9e1cf.png">

**Comment by timuric** [comment]
@krzysztofzuraw I think this can be an opportunity to change the popups to relative dates and absolute dates by default
