### ISSUE TITLE
Implement new UI for apps

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3123]
### What I'm trying to achieve

I want to have a new UI for the apps list.

### Describe a proposed solution

We should create a new UI for apps based on Figma.

### Acceptance Criteria 

- [ ] Apps list page looks like on Figma design

### Screenshots or mockups

![Image](https://user-images.githubusercontent.com/9116238/217269033-fe8704a3-fe68-41ff-a6d8-5019f5efc6e8.jpg)

**Comment by Droniu** [comment]
Fixed in #3154
