### ISSUE TITLE
Prevent jumping content after scrolling to the top or bottom of the screen

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3141]
### Description of the issue

Currently when scrolling vertically content jumps.

### Steps to reproduce the problem

1. See video for details but go to any page with vertical scrolling 

### Expected Result

Content does not jump

### Actual Result

Content jumps

### Screenshots

https://user-images.githubusercontent.com/9116238/217830729-cb9e0f62-135b-4ea7-823d-883a2eecb680.mp4

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.11.0`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
It no longer exists on newer versions. Closing
