### ISSUE TITLE
Login ask

### ISSUE THREAD

**Issue by frankl1m** [saleor/saleor-dashboard#3150]
I was studying you code for dashboard and for storefront. I saw some methods to login using user and password using graphql, both create new token and context load the user details as logued even if not exist Headers for Auth or Cookies, all is ok with it. So my ask is if exist any graphql method in your saleor store that i can use for example to pass as parameters my user auth bearer token in post data like query o mutation that can convert your context to use as logued user without need any Headers for auth or cookies. The idea is fast change from a user to another using multiples queries in same HTTP request and avoid slow process to login using user + password. My english bad, if need better explaination i repeat in another way

**Comment by peelar** [comment]
Hello @frankl1m 👋 

I am afraid I don't understand your question. Can you write down what you would like to do in points? Like so:

1. Run a mutation (example)
2. ...
3. ...

**Comment by frankl1m** [comment]
for example if i use this mutation TokenAuth($email: String!, $password: String!), sending anonymous request it log user internally and next queries in request are logued, so my ask is exist similar mutation for example like TokenAuth($tokenBearer: String!) that passing a token bearear of a user already loguead, can be able to log using the query for anonymous request
