### ISSUE TITLE
Do not preserve scroll when navigating from list to detail view

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3171]
### Description of the issue

We should not preserve scroll when navigating from list view to detail view.

### Steps to reproduce the problem

1. Go to any list view
2. Scroll into the middle or the end of the list
3. Click list item to display detail page

### Expected Result

The detail page is scrolled to the top.

### Actual Result

The scroll stays in the same place as on the list.

### HTTP request and response from the inspector

https://user-images.githubusercontent.com/9116238/219327687-df7712fb-ec17-400a-be0d-6cd952f22ec4.mp4

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.11.x` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
It no longer exists on newer versions. Closing
