### ISSUE TITLE
Attribute value is not editable 

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3181]
### Description of the issue
When creating a new attribute I add attribute value to it. If there is only 1 attribute I can't change it or delete it. If there is more I can change/remove all except the first.

### Steps to reproduce the problem

1. Start creating new attribute - configuration > attributes > create attribute
2. Assign a value
3. Click on the value row
4. Edit the value
5. Save

Also deleting the first value is not possible

### Expected Result
The first value should be editable 
…

### Actual Result

https://user-images.githubusercontent.com/124166231/219672036-1a2b1169-599d-4605-8715-725a701f6e7c.mov

`v3.11`

Operating system:

- [ ] MacOS

Browser:

- [ ] Chrome

**Comment by Droniu** [comment]
Fixed in #4266
