### ISSUE TITLE
Unknown webhook Events

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-dashboard#3200]
### Description of the issue

`WebhookEventTypeAsyncEnum` and `WebhookEventTypeSyncEnum` provides events that don't implement Event .
If such event is picked from on the webhook events page, `GraphiQL` shows an error `Unknown type ABC`. 

### Steps to reproduce the problem

1. Create or pick some some webhook in settings
2. Pick event eg `NotifyUser`, `Observability`

### Expected Result

Available events while picked should have no error in the `GraphiQL` explorer 

### Screenshots

<img width="977" alt="Screenshot 2023-02-15 at 09 25 02" src="https://user-images.githubusercontent.com/30683248/218975760-8af16560-3625-45c6-8a7e-ef2eebf9f594.png">

<img width="994" alt="Screenshot 2023-02-15 at 09 29 45" src="https://user-images.githubusercontent.com/30683248/218975712-0e449c09-c14e-4af6-8bdb-cd082d4561ac.png">

<img width="369" alt="Screenshot 2023-02-15 at 09 34 21" src="https://user-images.githubusercontent.com/30683248/218975604-936f7377-caba-45b7-9e02-b023c526cb7f.png">

_Originally posted by @szczecha in https://github.com/saleor/saleor-dashboard/issues/3099#issuecomment-1430946001_

**Comment by maarcingebala** [comment]
Related thread [here](https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1677856959577099).
