### ISSUE TITLE
Move app header to the dashboard

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3211]
### What I'm trying to achieve
We need to have a clear distinction between 3rd party apps embedded in the dashboard and the dashboard UI itself. It's needed for security reasons as we clearly can indicate where the app starts so no one can impersonate it.

### Describe a proposed solution
Let's move apps header to be rendered always by the dashboard

### Acceptance Criteria 
- [ ] Dashbaord is rendering app header
- [ ] The app header takes information from manifest and render it properly (icon, title, links)

### Screenshots or mockups
<img width="1302" alt="Screenshot 2023-02-23 at 10 26 57" src="https://user-images.githubusercontent.com/7943292/220868043-2a5d5693-976d-420b-9e06-54c56ab96f46.png">

**Comment by lkostrowski** [comment]
For "color and logo", lets use a fallback (like in the /apps root page), until we deliver this
https://github.com/saleor/apps/issues/186 (cc @przlada )

For "name" - its available 👍 

For "Repository" - its available, but optional. I suggest to display it from manifest at the moment

For "Request a feature" - this is not available, I suggest to use `manifest.homepageUrl` 

In the future we can add fields to manifest that will "inject" buttons there. But app can link to its roadmap/feautre requests inside the iframe

**Comment by lkostrowski** [comment]
@krzysztofzuraw Here are preview deployments with apps without Title Bars
https://github.com/saleor/apps/pull/209

You can check how they look together

**Comment by krzysztofzuraw** [comment]
@pflis1 please check how it looks on https://fix-3211-app-header.dashboard.saleor.rocks/apps/QXBwOjY0/app/importer
