### ISSUE TITLE
Implement header for product list view

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3234]
### What I'm trying to achieve
Update the existing top header for the product listing view.

### Acceptance Criteria 

- [ ] Search input that allows browsing products
- [ ] Filtering button that opens the filtering menu
- [ ] Toggle switch, for switching between card and table (grid) view

**Comment by poulch** [comment]
PR https://github.com/saleor/saleor-dashboard/pull/3346
