### ISSUE TITLE
It is not clear that webhook list is loading

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#3243]
### Description of the issue

https://user-images.githubusercontent.com/41952692/222119186-7eb8b57f-aa41-433d-a95c-b5ba936de038.mov

### Steps to reproduce the problem

1. Go to configuration
2. Go to webhook list

### Expected Result

When in loading state, skeletons are displayed

### Actual Result

Screen is almost blank

### System information

Dashboard version:

`v3.11.0-dev`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
Already Fixed
