### ISSUE TITLE
Implement static datagrid in orders view

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3256]
### Acceptance Criteria 
- [ ] I can view a list of orders in datagrid
- [ ] I can change the order of columns
- [ ] I can sort by column acs/desc
- [ ] I can pick a column in the column selector
- [ ] I can paginate orders and change the number of products per page

**Comment by wojteknowacki** [comment]
Sticky column functionality is disabled when removing other column from grid


https://user-images.githubusercontent.com/124166231/226911966-41bb8069-2d55-4033-98aa-4d4fbdd2eb8e.mov
