### ISSUE TITLE
Implement filtering within the dashboard

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3272]
### What I'm trying to achieve
Using components created in: https://github.com/saleor/saleor-dashboard/issues/3085 please implement filtering login for the dashboard

### Acceptance Criteria 
- [ ] Implement filtering for the product listing page
- [ ] For filtering use attributes, channels, product types (use the same filer sets as it's used now)

RFC: https://github.com/saleor/saleor-dashboard/issues/3702

**Comment by wojteknowacki** [comment]
No border looks like a bug to me


![Image](https://github.com/saleor/saleor-dashboard/assets/124166231/b0ed4ef4-8873-4599-8d68-83a80c17c5eb)

**Comment by wojteknowacki** [comment]
Category search when operand IN: search input is unstable, changes shape and content

https://github.com/saleor/saleor-dashboard/assets/124166231/4b00cad3-0ad2-4ea9-8a69-83095ccf9d80

**Comment by wojteknowacki** [comment]
The user can not see active filters:
- Add filter WHERE Category IN Accessories
- Click save
- Open filters once again
- Accessories not visible
- 

https://github.com/saleor/saleor-dashboard/assets/124166231/0d0f5940-a4ee-4832-9b86-b19ec3b24e14

**Comment by wojteknowacki** [comment]
Chaining filters - WHERE CATEGORY AND Adding filter Price which needs Channels to work and then removing Price filter keeps Channels visible and unable to save

https://github.com/saleor/saleor-dashboard/assets/124166231/23573156-0a89-4106-ac37-f4bafde44665

**Comment by wojteknowacki** [comment]
Filter collections error

https://github.com/saleor/saleor-dashboard/assets/124166231/29046720-1751-464e-b130-77bdf95baddc

**Comment by wojteknowacki** [comment]
Same results are displayed when: 
- WHERE Has category is No
- WHERE Has category is Yes
Looks like filter WHERE Has category is No is not working correctly

https://github.com/saleor/saleor-dashboard/assets/124166231/9682bbb8-2be5-47b4-a6fd-d1ae72eac33c

**Comment by wojteknowacki** [comment]
Same results are displayed when:

WHERE Has giftcard is No
WHERE Has giftcard is Yes
Looks like filter WHERE Has giftcard is No is not working correctly

**Comment by wojteknowacki** [comment]
Misleading naming - `Has giftcard` suggest product includes gift card but in reality Product is gift card. Suggested change: `Has giftcard` -> `Is giftcard`

**Comment by wojteknowacki** [comment]
As a user I am not aware I can pick other condition in Where part than those displayed - no info I can use for example attributes

**Comment by wojteknowacki** [comment]
When user reaches to many filters dialog is not scrollable

![Image](https://github.com/saleor/saleor-dashboard/assets/124166231/1585a717-3245-401b-9c44-82145d852eae)

**Comment by wojteknowacki** [comment]
Button clear all fields should not close filter dialog
