### ISSUE TITLE
Unable to create product on Safari

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3283]
1. Create new product on Safari 
2. Choose product type: CreateProSku85840 or cushion
3. Click save button
Result:

![Image](https://user-images.githubusercontent.com/25908728/222737346-986690e9-0e29-4bba-9e1d-3381605a339b.png)

The product is created, but it is not visible on the UI side 
ENV: https://v312.staging.saleor.cloud/dashboard/products/

**Comment by poulch** [comment]
I also tried but can not reproduce this error. Could you confirm that this error still occurs and provide us safari version and macOS

**Comment by michalina-graczyk** [comment]
I checked it today and it also works on my side. 
Safari Version 16.1 
macOS 13.0

**Comment by poulch** [comment]
If we can not reproduce the bug I am closing this issue.
