### ISSUE TITLE
Migrate Products list page to new MacawUI components [TopNavMenu]

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3285]
### What I'm trying to achieve

I want to have a Product list page with the new MacawUI components

### Describe a proposed solution

Migrate to the new TopNav menu items

### Acceptance Criteria 

* [ ] New TopNav menu items are present

### Screenshots or mockups
![CleanShot 2023-03-06 at 11 11 31@2x](https://user-images.githubusercontent.com/9116238/223080654-e4df8d6b-333f-486e-9803-f7dfc38b5896.jpg)

**Comment by krzysztofzuraw** [comment]
@pflis1 or @timuric please take a look at screenshots for Acceptance:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/9116238/223355111-453ed8d7-da1d-4ae8-89db-af657cc032f1.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/9116238/223355168-fb0ca623-a2df-4346-89b1-01e6e5c8a261.png">

**Comment by Droniu** [comment]
Merged with #3296
