### ISSUE TITLE
MacawUI - UI issues on safari

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3288]
When you minimize a window the frame is missing.

![Image](https://user-images.githubusercontent.com/25908728/223068785-d1f4d1ee-5eb9-4c1f-8ff4-83c15d2cfd8f.png)

![Image](https://user-images.githubusercontent.com/25908728/223069153-178b5255-7776-44d4-865d-e367f6c80415.png)

**Comment by wojteknowacki** [comment]
We do not support such small screen resolutions
