### ISSUE TITLE
Digital content management

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-dashboard#33]
Support for digital content fulfillment in the backend was added in PR mirumee/saleor#2098. Now we need to implement related management views in Dashboard 2.0. Mockups are available in Figma in the "PRODUCTS DIGITAL" section.

**Comment by Boquete** [comment]
Are mockups public? Would appreciate attaching them

**Comment by Boquete** [comment]
Any update?

**Comment by joaonice** [comment]
Any updates on this issue?

**Comment by LudoMon** [comment]
Hello, 

Thank you for your work, I love it!

This feature would definitely be an amazing improvement for me too, do you plan to implement it? Since it exists in the backend API, I suppose this would be too bad not to have it in the interface.

Thank you!

**Comment by DropSnorz** [comment]
Hi ! I agree. It would be great to have this feature. 

@maarcingebala can we reopen this issue ?

Thanks.

**Comment by maarcingebala** [comment]
Sure, it's still on our roadmap.

**Comment by truonghdpk** [comment]
I'm waitting too

**Comment by simon-online** [comment]
I'm wanting to add support for digital content management by customising a new v3 Saleor store in the next few months however I'm unsure as to what the best way to go about it is considering that this will eventually become functionality that is built into the Saleor Dashboard. So I want to avoid spending too much time on a solution that will eventually be retired and I want to avoid changing any core code so it will make it easy to update to newer versions of Saleor in the future.

I'm aware that the API has the digitalContent(s) queries and the digitalContentCreate, digitalContentDelete, digitalContentUpdate and digitalContentUrlCreate mutations.

However for my use case all digital content URLs are never going to expire and will be automatically fulfilled for every digital product that is purchased. So I'm thinking the simplest solution might be to create a private product variant file attribute that can store the digital content file. Then I could create a plugin with a product_variant_updated callback method that looks for product variants with a new digital content file and properly creates or updates the digital content file in a similar way to the digitalContentCreate or digitalContentUpdate API requests. Likewise the same could be done for the product_variant_deleted callback method to delete the digital content file in a similar way to the digitalContentDelete API request.

Does this sound like a feasible solution?
Do you have any advice on how best to go about this or things to watch out for?

**Comment by simon-online** [comment]
Does this mean adding, managing and fulfilling digital content for products will soon be possible in the Saleor dashboard?

**Comment by simon-online** [comment]
@andrzejewsky If you can confirm what we can expect soon that will help with our planning. Thanks

> Does this mean adding, managing and fulfilling digital content for products will soon be possible in the Saleor dashboard?

**Comment by shoesack** [comment]
Hi, probably i missed it but it seems this feature still doesn't exist in the newest dashboard version 3.19.10 right? Any future plans on this?
