### ISSUE TITLE
Missing shadow on popup

### ISSUE THREAD

**Issue by poulch** [saleor/saleor-dashboard#3311]
### Description of the issue
Poper component from material-ui doesn't have a shadow around, and it looks bad.
…

### Steps to reproduce the problem

1. Go to the product list
2. Choose the product and click on it
3. Try to add new media, a then a little popup appears

### Expected Result
Popup should have shadow
…

### Actual Result

…

### Screenshots

![Screenshot 2023-03-08 at 13 05 31](https://user-images.githubusercontent.com/16362049/223964080-fa527869-8f9c-4000-8e10-17b844e23a32.png)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
It no longer exists. Closing
