### ISSUE TITLE
Create Page Type page looks empty

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3336]
### Description of the issue
Create Page Type page has too many spaces, it doesn't look good from the UX perspective. 

![image](https://user-images.githubusercontent.com/25908728/224332885-571a8e93-24c6-44e9-88dc-955b16076e49.png)

**Comment by fedexin40** [comment]
Hello @michalina-graczyk what is the purpose of content, I was trying to figure out and wondering if you can give a clue

**Comment by timuric** [comment]
@fedexin40 Page types allow you to create groups of attributes for pages, for example: Title, Description, Image
Which allows you later to create structure page content (See Content in navigation)

**Comment by wojteknowacki** [comment]
Fixed in newer versions like 3.15
