### ISSUE TITLE
Shrinking the window horizontally makes name of products crashing

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3338]
1. Go to products -> custom filters 
2. Shrink the window 
Current results: Name of products looks badly

![Image](https://user-images.githubusercontent.com/25908728/224346361-00cc1f53-6857-432a-8d63-b1f64edc7174.png)

**Comment by Droniu** [comment]
This will no longer be a problem after #3296 is merged. This PR changes whole product list view.
