### ISSUE TITLE
Dobule scrollbar with filckering on all dialogs with infinity scroll

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3344]
## Description of the issue
When user opens for example product selector modal for draft order it get's double sidebar that is flickering.
Those dialogs can also be infected:
- ShippingMethodProductsAddDialog
- AssignMembersDialog
- OrderProductAddDialog
- AssignVariantDialog
- AssignProductDialog
- AssignContainerDialog
- AssignAttributeDialog

### Steps to reproduce the problem

1. Go to draft order
2. Select product

### Expected Result

There is one scrollbar and there without filckering

### Actual Result

There are two scrollbars with one of the filckering

### Screenshots

https://user-images.githubusercontent.com/9116238/224684232-e4f1baea-e6e4-4c25-8207-d796c8f92728.mov

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.13-dev`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
Issue still present on Firefox
