### ISSUE TITLE
In graphiql area some details are hidden

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3360]
### Description of the issue
In GraphiQL details are hidden but should be visible .

### Steps to reproduce the problem

1. Go to orders
2. Select any order
3. Click on pinion icon and select 'Open this order in graphiql'
4. Hover on settings

### Expected Result
Setting information is above the page instead of being hidden. More examples in Actual results

…

### Actual Result
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/25908728/225014607-7d7eb8d5-7383-4a2f-a518-bd2e0dfcc36a.png">
**What is more, when I hover on some input in Query I can't see hints. In playground hints are visible, here are hidden.**

Another case: 

<img width="1684" alt="Screenshot 2023-03-13 at 20 21 06" src="https://user-images.githubusercontent.com/25908728/225016324-20bc468f-4f86-4c27-9a73-ff16d1b60c2c.png">
…

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

dashboard v3.13.0-dev

Core version:

core v3.13.0-a
Operating system:

- [ ] Windows
- [ ] Linux
- [ X] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [X ] Chrome
- [ ] Edge
- [X ] FF

**Comment by zaiste** [comment]
Fixed in #3333
