### ISSUE TITLE
Wrong background for elements in product detail view

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#3367]
### Description of the issue

Some element on ProductView has different background color in dark mode. The problem does not exist in light mode. (Media and Variants section).

### Steps to reproduce the problem

1. Go to the product detail view
2. Scroll to the media and variant section
3. Change the theme from light to dark

### Expected Result

Colors are applied consistently to both light and dark modes.

### Actual Result

There is a difference between dark and light modes.

### Screenshots

![image (1)](https://user-images.githubusercontent.com/9116238/225304179-42a9c5ae-b7d1-4859-8f94-3127d0df3adb.png)
![image](https://user-images.githubusercontent.com/9116238/225304183-9f65e6af-7aa4-4a46-8e54-183b71a3b931.png)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.13-dev`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by andrzejewsky** [comment]
Macaw related, closing for now.
