### ISSUE TITLE
Implement filter saving dropdown

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3373]
### What I'm trying to achieve
We want to allow users to save their search and selected filter under some name. 

### Acceptance Criteria 
- [ ] As a user who doesn't have a saved preset I see the `All products` title with a tooltip on the mouse over
- [ ] As a user I should be able to save selected filters with search queries under the given name
- [ ] As a user I should be able to select previously saved presets from the dropdown 
- [ ] As a user I should be able to remove saved preset by clicking on the cross icon next to the preset name in the dropdown
- [ ] As a user I should be able to update the correctly selected preset by clicking the Update button when something is changed
- [ ] As a user I should be able to save selected filters and search a new one instead of update current one

**Comment by wojteknowacki** [comment]
1. Same names of presets should not be allowed
2. No scroll on the product presets list
<img width="929" alt="Zrzut ekranu 2023-04-5 o 12 29 01" src="https://user-images.githubusercontent.com/124166231/230055144-8f6bb1e0-95b0-4c64-99ca-b9e69e1e0fdb.png">
3. When a user on the preset list view enters the details view of the product:
- using the back header back button redirects to the list view with all products
- using the browser back button redirects to the list view with preset products view
4. updating the preset makes results reload once again
https://user-images.githubusercontent.com/124166231/230062374-809d4d19-9bd4-4db9-91bd-b51774018c85.mov
5. product preset does not keep the state when interacting with the search:
https://user-images.githubusercontent.com/124166231/230065480-24bff385-b2a3-4b6d-a474-030a3a6ab938.mov
6. should not allow saving empty preset ( when 0 results )
7. When deleting the preset when another preset is active should result in an active preset search active - now we change to all products preset automatically 
https://user-images.githubusercontent.com/124166231/230073335-16d9bb8f-515a-49b6-9207-001592d12f6e.mov

**Comment by wojteknowacki** [comment]
8. Users don't see created presets on different browser than the one used to create preset

**Comment by wojteknowacki** [comment]
Horizontal scroll on presets dropdown picker - Firefox 

![Image](https://user-images.githubusercontent.com/124166231/230295058-3480c951-2db0-49f4-b947-673724645d04.png)

**Comment by wojteknowacki** [comment]
@timuric could you review those comments in the context of UX improvements?

**Comment by timuric** [comment]
@wojteknowacki good points

**Comment by poulch** [comment]
PR https://github.com/saleor/saleor-dashboard/pull/3412
