### ISSUE TITLE
Add cypress tests to checkout app in dashboard demo

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3457]
Please provide e2e test with this scenario:

1. Go to https://staging-demo.saleor.io/dashboard/ -> apps -> checkout
2. Check if page is loaded correctly, and there are no 400 issues 
3. Paste demo checkout url https://demo.saleor.io/checkout/?checkout=Q2hlY2tvdXQ6NThjNzEyYjUtMjVmMC00MmRhLWI4ODUtYzliMzZmZjZmMGE5&locale=en-US&channel=channel-pln&saleorApiUrl=https%3A%2F%2Fdemo.saleor.io%2Fgraphql%2F&domain=demo.saleor.io

Expect checkout to be visible

![Image](https://user-images.githubusercontent.com/25908728/229806452-2b732f1a-488f-433a-967f-a3bb37b7bbc8.png)

This test should be added to the scope of critical tests.

**Comment by wojteknowacki** [comment]
Due to change of roadmap this ticket will not be covered
