### ISSUE TITLE
UX issue when changing input value

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3459]
When editing the shipping configuration and clicking `Enter` on the keyboard dashboard, it closes the current view and returns to the previous view without saving. Also unsaved data modal doesn’t appear.

https://user-images.githubusercontent.com/124166231/230001210-d1014412-d1cd-43a3-aeb5-00a78535e77d.mov

**Comment by krzysztofzuraw** [comment]
Cannot reproduce
