### ISSUE TITLE
GraphiQL response should be scrollable in dry run mode

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-dashboard#3465]
### Description of the issue
I'm using the dry run mode to test webhook responses. If the response exceeds the visible area there is no way to scroll down to see it fully.

### Steps to reproduce the problem

1. Create a webhook with multiple fields, or fields that return longer responses (example `content` field in Pages with a lot of content)
2. Run the dry run to receive the example response.

### Expected Result
The response should be scrollable.

### Actual Result
The response is not scrollable.

### Screenshots
![image](https://user-images.githubusercontent.com/5421321/230062762-9c6c3196-4a75-41dd-a6bb-52dbfe881922.png)

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`dashboard v3.13.0-dev`

Core version:

N/A

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome Version 111.0.5563.146 (Official Build) (arm64)
- [ ] Edge
- [ ] Other

**Comment by 2can** [comment]
Fixed in https://github.com/saleor/saleor-dashboard/pull/3549
