### ISSUE TITLE
Pagination not accurate

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3471]
### Description of the issue
When filtering items which total nr in system is 11 and set only 10 items per view in list view:
on first page there are 10 items
on second page are 4 items ( 3 the same as on 1st page)
…

### Steps to reproduce the problem

1. filter products with 11 records in system
2. set 10 items per page 
3. go to 2nd page of pagination

### Expected Result
Pagination should display as many records as set. No doubled records on different pages of pagination
…

### Actual Result

https://user-images.githubusercontent.com/124166231/230104114-022d8a3f-f54c-4ec3-b569-7e98e96b6a0d.mov

Dashboard version:

`v3.12` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by poulch** [comment]
I close this issue because of the issue in on the core side. I've created a separate issue on their board.
CORE issue https://github.com/saleor/saleor/issues/12555
