### ISSUE TITLE
Quantity amount change unnoticeable for user

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3475]
### Description of the issue

An issue with creating an order view when setting the quantity of variants to a big number like 345345345345

### Steps to reproduce the problem

1. Go to the draft order list and select draft order
2. Add product if not added before
3. Add address and user
4. Set shipping method
5. Set quantity to a very big number for example 345345345345
6. Save order

### Expected Result

OR The user informed that the quantity amount was changed  
OR Not allow to save order and point to quantity fields that make an error

### Actual Result
Order is saved and quantity is changed unnoticeable 

### System information

Dashboard version:

`v3.12` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by Droniu** [comment]
Fixed in #3325, related backend bug - https://github.com/saleor/saleor/issues/12771
