### ISSUE TITLE
Remove feature flags for Transactions in dashboard

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-dashboard#3490]
Remove feature flags related to Transactions in `saleor-dashboard`.
This can be merged once Saleor 3.13 is released

Fix:
- [x] `INFO` event doesn't show message

**Comment by szczecha** [comment]
Removing this flag will require some fixes in E2E 
![image](https://user-images.githubusercontent.com/30683248/233062516-1f1891a1-8874-47d8-9707-6ae845725bdb.png)
orders.js and channels.js

We can create a new function for updating order settings via API:
updateChannelOrdersSettings
(channelId,
automaticallyConfirmAllNewOrders = true,
automaticallyFulfillNonShippableGiftCard = true,
markAsPaidStrategy = "PAYMENT_FLOW"
) 
send mutation channelUpdate with OrderSettingsInput
