### ISSUE TITLE
Invalid events for tax calculation in the webhook subscription query

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor-dashboard#3517]
### Description of the issue
Unable to correctly setup webhook for checkout, order calculate taxes

### Steps to reproduce the problem

1. Go to Configuration -> Webhooks & Events
2. Create an app with Handle Taxes permission
3. Create webhook with sync events: Checkout calculate taxes, Order calculate taxes

### Expected Result
The correct event in the subscription query

### Actual Result
Invalid events occur in subscription query
<img width="1020" alt="Screenshot 2023-04-18 at 14 48 26" src="https://user-images.githubusercontent.com/30683248/232784340-e3bc4daf-c971-4a79-b536-8c9e085bce4a.png">

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:
`v3.12.3`

Core version:
`v3.13.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by 2can** [comment]
@szczecha I couldn't replicate with dashboard `v3.13.0-dev`, core `v3.14.0-a`,  could you re-check ?

**Comment by szczecha** [comment]
Yes, I confirm on core v3.14.0-a when I click on subscription events checkout/order Calculate taxes it no longer shows those events on the subscription query and it allows to save webhook without the subscription query. So I'm closing this ticket.
