### ISSUE TITLE
Remove ligatures from playground

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-dashboard#3529]
GraphQL syntax doesn't benefit from ligatures, and can be confusing when data is displayed 
![image](https://user-images.githubusercontent.com/4006792/233348099-ac619b53-30fb-473e-8e13-929e5bdf302b.png)

`.graphiql-container * {
  font-variant-ligatures: none;
}`

**Comment by 2can** [comment]
Done in https://github.com/saleor/saleor-dashboard/pull/3549
