### ISSUE TITLE
Vanished attribute metadata after udate

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-dashboard#3558]
### Description of the issue
There is an issue with attributes metadata. I’m entering attribute with metadata, and private metadata. I’m updating metadata. Private metadata are vanished after refreshing page.
…

### Steps to reproduce the problem

1. Create attribute with metadata and private metadata, save
2. Update metadata
3. Refresh page

### Expected Result
Metadata are updated, private metadata still displayed
…

### Actual Result
Private metadata vanished
…

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by michalina-graczyk** [comment]
[Untitled_ Apr 27, 2023 10_54 AM.webm](https://user-images.githubusercontent.com/25908728/234812508-0ca28f39-ccde-484e-8b61-0407d6560d70.webm)
Steps:
1. Add new metadata and new private metadata
2. Edit metadata field and value
3. Click Save
Current result: 
The last field of private metadata is dissapearing for a while
