### ISSUE TITLE
Orders with Transactions 

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3574]
### Description of the issue

1. Status label needs a page refresh to show the correct status

https://user-images.githubusercontent.com/124166231/234547672-908d047d-a32b-4ee2-b52d-11042b99f01d.mov

2. White space covers variants on the grant refund view

https://user-images.githubusercontent.com/124166231/234547911-401c4de0-af9a-43ce-81b7-a9adf8d57bbb.mov

3. Order history notes UI fail
![image](https://user-images.githubusercontent.com/124166231/234548058-9999279c-4c7c-4116-a5fb-590e128e1287.png)

4. Manual capture list view 
![image](https://user-images.githubusercontent.com/124166231/234548181-9133c648-b0a9-431d-9494-01b391ae97b6.png)
![image](https://user-images.githubusercontent.com/124166231/234548213-7af13cc5-33e8-453d-8f34-99d3ad034b1c.png)

5. When editing the grant refund page - the back button does not trigger the confirmation dialog when changes made

6. When using Chrome suggestion to complete the refund reason text field:
![image](https://user-images.githubusercontent.com/124166231/234548556-85f92c2a-7e4c-4477-88c3-39f2acf27e7d.png)
![image](https://user-images.githubusercontent.com/124166231/234548590-f6f5c87e-18c5-4447-b8c0-743435db2764.png)

7. Grant refund is not mentioned in the order history

8. Send refund screen & orders details screen:
- PSP reference not visible
- refund and capture labels not aligned
- when PSP is long UI fails
![image](https://user-images.githubusercontent.com/124166231/234548909-22062211-c72c-4888-b60c-1fae467ff92d.png)
![image](https://user-images.githubusercontent.com/124166231/234549787-917c3284-c33c-40f3-aa30-1e563cd58823.png)

9. Focus issue: 
https://user-images.githubusercontent.com/124166231/234549922-9a89e093-2157-4776-a72e-70675b850bae.mov

10. Capture manual transaction dialog:
The description input has no counter which limits its length but when adding:
`Lorem ipsum dolor sit amet consectetur adipiscing elit lobortis facilisi, lacinia sem ac non nullam dis phasellus platea, hendrerit diam laoreet nulla eget est malesuada odio. Luctus nibh sagittis libero blandit ridiculus praesent ultricies faucibus proin sollicitudin eleifend maecenas, pellentesque taciti per sem fermentum ad suspendisse dictumst tincidunt dictum. At sapien non leo ornare nascetur nunc magnis lacus natoque sed laoreet, justo tristique sociosqu mattis quis sollicitudin ultrices vehicula neque. Mus et pulvinar faucibus sapien mauris luctus varius, magnis ultricies massa nisi porttitor.` 
as description, there is an `internal server error` 
❗ please check other inputs as well in this dialog

11. Manual capture list view:
- horizontal scrolling
- date squeezed

https://user-images.githubusercontent.com/124166231/234559033-57ace9eb-eb20-4588-b4ca-fb71deac0f7a.mov

…

### Steps to reproduce the problem

1. Make sure the order you create is in the channel which has the toggle turned on:
![Zrzut ekranu 2023-04-26 o 12 35 36](https://user-images.githubusercontent.com/124166231/234550230-2b1ebee7-f4d4-440d-9a5e-4a184162e310.png)

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by witoszekdev** [comment]
7. It's an issue in Saleor Core
9. It's due to psp reference beeing an empty string `""`

**Comment by mmiszy** [comment]
Fixed now in https://github.com/saleor/saleor-dashboard/pull/3557

@wojteknowacki @witoszekdev 

1. Fixed.
2. Fixed in two places.
3. Fixed – dates never wrap now.
4. Limited length of PSP reference and description to 512 chars; added max-width and wraps.
5. Fixed.
6. –
7. –
8. Fixed.
9. Fixed.
10. Fixed.
11. Dates never wrap now. However, we can't completely avoid horizontal scrolls on small screens. I made my best to improve it.
