### ISSUE TITLE
Column picker - dynamic columns should not be togglable

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#3686]
<img width="642" alt="image" src="https://github.com/saleor/saleor-dashboard/assets/41952692/1431c3ce-a074-4d25-a990-aa2a25cbb31f">

Toggles in dynamic columns should be replaced with remove icon buttons.

This will simplify architecture a bit - no need for using dual local storage, because of lack of indeterminate state of dynamic columns.

### Acceptance Criteria
*Note: currently, dynamic columns which are eligible for testing are attributes on product list.*
1. Dynamic (custom) columns are no longer togglable. Adding them from left side of column picker makes them selected.
2. Instead of a toggle, there is a remove button, which should remove custom column from both datagrid and `Custom` section of column picker.
3. Unselecting a checkbox in left side of column picker currently removes the column - this behaviour should be preserved, so that both remove icon and unselecting a checkbox achieve the same result.
4. Columns should be ordered by recently added at the end and this order should be preserved after refresh. (If you manually move the column in datagrid, this state will not be persisted, this will be worked on in #3682). 
5. Column picker should initialise default columns on first login on new device (when there is no listConfig in local storage).
6. There should be no regressions, so search, pagination, resizing, persistence, UI etc should work the same way as it was in original implementation (#3514)

**Comment by wojteknowacki** [comment]
Please verify if this PR fixes also this https://github.com/saleor/saleor-dashboard/pull/3514#issuecomment-1589344981
