### ISSUE TITLE
[RFC]: New filtering design in the product listing page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3702]
### Short description of the feature

The new filtering experience should better present filters to the user and allow them to easily create complex filters. 
Filters should work with the product list table and allow to filter of products by fields defined in [GraphQL schema](https://docs.saleor.io/docs/3.x/api-storefront/products/inputs/product-filter-input).

### Full description

We should create a new filtering UI in place of the current one on the product list page.

The new solution should allow a better overview of what options the user has when filtering products. It should also allow more complex filters that will be implemented by Saleor [Core](https://github.com/saleor/saleor/issues/11432). Lastly, filters should adapt to the user's needs and not confuse them with unnecessary data upfront.

The new solution should be presented as a single button, once clicked, the filtering mechanism will be presented within a popover. The mechanism is consisting of multiple rows, where each represents an expression of our filter. Within the expression, we can define the filter operand _**A**_ (eg category, product type, price, color, etc.), its condition _**B**_ (is, between, greater than, less than), and given value _**C**_ (presented as dedicated form control: input, number, dropdown). Users can add multiple rows (expressions), by clicking add filter button **_E_** and clicking "x" for deleting.

![CleanShot 2023-08-03 at 12 42 08@2x](https://github.com/saleor/saleor-dashboard/assets/9116238/f8e99c44-9f91-4bb6-bf3e-54599988fd89)

Clicking the _**D**_ button will make a request to GraphQL API and update the URL with newly selected filters.

The implementation should be delivered in the following parts:

1. Narrow filtering - we skip the part of grouping and between the expression, we keep the "and" condition by default (the user cannot change that). This is the default behavior that we currently have in the API
2. Adding conditions between expressions - allow the user to pick between and/or
3. Add grouping - add an ability to group expressions (nesting)

**Note**: Currently nesting and changing conditions are available for attributes, thus we want to deliver filtering feature for products as narrow first.

### Acceptance Criteria

- [ ]  As a user, I want to see the filtering mechanism (available within the popover)
- [ ]  As a user, I want to be able to retrieve the selected filters and apply them to the product list
- [ ]  As a user, I want to be able to edit or delete selected expressions
- [ ]  As a user, I want to be able to see selected filters when I came back to the dashboard
- [ ]  As a user, I want to share filters with others via url
- [ ]  As a user, I want to filter by attributes with types:
  - [ ] Dropdown
  - [ ] Multiselect
  - [ ] Numeric
  - [ ] Boolean
  - [ ] Date
  - [ ] Datetime
- [ ] As a user, I want to filter by static fields: category, price, product type, channel, collection
- [ ] As a Saleor, we want to keep constraints on fields (`price`, `isVisibleInListing`, `isAvailable` and `isPublished`) that disallow removing `channel` when one of the previously defined fields is selected

### Additional notes

- Filtering feature will be implemented by using MacawUI components. They will be fully presentational so the developer will be able to build their own filter expressions if needed
- MacawUI will also share a fully working filter component (with the composition of presentational ones), with some pre-defined contract, to cover most of use cases of filtering (eg. dashboard)
- Attached screenshots are the only examples, colors, sizes, paddings, and margins can be updated. Please treat this as a mockup

**Comment by lkostrowski** [comment]
How the state will be persisted? Will it be memory, or URL? 

Saving in URL will be awesome to keep persistence (refresh and share links). I only worry about maximum URL length for complex queries.
