### ISSUE TITLE
Implement column picker for the orders (including drafts)

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3754]
### Acceptance Criteria 
- [ ] As a user I should be able to pick product name column
- [ ] As a user I should be able to pick product SKU column
- [ ] As a user I should be able to pick quantity column
- [ ] As a user I should be able to pick price column
- [ ] As a user I should be able to pick total column
- [ ] As a user I should be able to pick variant name column

**Comment by poulch** [comment]
Update: metadata in colulm picker will be add in this task: https://github.com/saleor/saleor-dashboard/issues/3378
