### ISSUE TITLE
Not clickable buttons on orders view

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#3775]
Not whole elements are clickable on orders view.  Go to draft order with selected products. Click `...` next to any product. 

Expected result:
whole buttons `delete` and `product details` are clickable
Actual results:
videos

Same when you go to order but not draft - open in new tab button is not entirely clickable

**Comment by krzysztofzuraw** [comment]
Duplicate of https://github.com/saleor/saleor-dashboard/issues/3776
