### ISSUE TITLE
[Bug]: can't change attribute value on new attributes

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#3817]
### Description of the issue

When creating new attributes, it is impossible to delete/edit attribute values

### Steps to reproduce the problem

1. Create new attribute
2. Select dropdown as type
3. Assign attribute
4. Try to change its name
5. Try to delete it
6. There is no effect

### What did you expect to happen?

Attribute value should be changeable and deletable during attribute creation proccess

### Additional information

https://github.com/saleor/saleor-dashboard/assets/41952692/d5d2b1a0-d9b4-40a9-a909-f02b3797f4cd

### Environment

Browser and version: 1.51.118 Chromium: 113.0.5672.126 (Official Build) (x86_64) 
OS and version: macOS Ventura 13.4
Dashboard version: 3.15.0-dev
Core version: v3.15.0-a.0

**Comment by michalina-graczyk** [comment]
This issue still exist on main
