### ISSUE TITLE
Apply datagrid to attributes page

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3979]
### Describe a proposed solution
Apply read-only datagrid on the attributes page along with new column picker

### Acceptance Criteria 

- [x]  As a user i should see attributes entries rendered within the table (grid)
- [x]  As a user i should be able to use all of the functionalities that datagrid has in the other views (sorting, d&d columns)

**Comment by michalina-graczyk** [comment]
When I remove attribute the `d` letter is missed

![Image](https://github.com/saleor/saleor-dashboard/assets/25908728/06c98c4a-425e-4af1-8fb6-804b2b7d3d6c)
