### ISSUE TITLE
[Feature] Apply new column picker to the variants grid

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#4007]
### What I'm trying to achieve
By using new column picker we should keep the same functionality as we have with the old implementation.

### Acceptance Criteria 
- [ ] As user I can pick sku
- [ ] As user I can pick variant name
- [ ] As user I can pick channels and its prices
- [ ] As user I can pick warehouses and its stocks
- [ ] As user I can pick attributes

**Comment by wojteknowacki** [comment]
Depends pf scroll position picker can open in position which unable user to interact with dynamic columns


https://github.com/saleor/saleor-dashboard/assets/124166231/6a663ac1-1cfc-4982-b1a7-399fae39a337

**Comment by wojteknowacki** [comment]
Search in dynamic columns should not be case sensitve

https://github.com/saleor/saleor-dashboard/assets/124166231/7aa8cbc6-efd0-4bbe-adbc-951e726843b2

**Comment by wojteknowacki** [comment]
Mismatch when adding new channel as available
- Switching availability and setting a new channel available
 - new channel is not displayed on grid
- Open column picker
- Go to dynamic columns and open channels
- Newly added channel is checked as it was added to data grid

https://github.com/saleor/saleor-dashboard/assets/124166231/20eb90e3-8b35-4c9f-a262-41aa7e8fdec4

**Comment by wojteknowacki** [comment]
- got to product details
- extend variant grid cell ( random - it should work )
- add new columns from the picker 
- grid UI jumps to the end of grid or glitches

https://github.com/saleor/saleor-dashboard/assets/124166231/4acd4f74-aabc-43ce-9fd5-3535ce016189
