### ISSUE TITLE
Add setting within the channel configuration that allows to make order without a payment

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#4014]
Ref: https://github.com/saleor/saleor/issues/13016
### Acceptance Criteria 

- [x] Checkbox with `Allow unpaid orders` is added on channel details page
- [x] Checkbox with `Allow unpaid orders` is added on channel create page
- [x] `Mark as paid` toggle is replaced with checkbox for consistency

### Other solutions I've tried and won't work
…

**Comment by michalina-graczyk** [comment]
tested
