### ISSUE TITLE
Add `defaultTransactionFlowStrategy` to Dashboard

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-dashboard#4050]
Add a toggle for [`OrderSettings.defaultTransactionFlowStrategy`](https://docs.saleor.io/docs/3.x/api-reference/orders/inputs/order-settings-input#code-style-fontweight-normal-ordersettingsinputbdefaulttransactionflowstrategybcodetransactionflowstrategyenum-) in Channel Settings page

**Comment by timuric** [comment]
Copy suggestion:

[x] - Authorize transactions instead of charging
When enabled, all transactions would require an additional step to be charged. (Learn more)

**Comment by timuric** [comment]
@witoszekdev requires docs https://github.com/saleor/saleor-docs/issues/863
