### ISSUE TITLE
[Bug]: Misleading copy

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-dashboard#4397]
### Description of the issue

Modal mentions paid subscriptions that don't exist
![image](https://github.com/saleor/saleor-dashboard/assets/4006792/871f305b-cc29-4412-813d-b2fabe865545)

### Steps to reproduce the problem

Delete app from appstore

### What did you expect to happen?

Show message: 

Deleting the app will also remove all its settings.

### Environment

Browser and version: …
OS and version: …
Dashboard version: …
Core version: …

**Comment by amitsgh** [comment]
Subject: Request to work on issue

Dear @timuric,
I'd like to work on above issue. Kindly consider assigning it to me.
Furthermore, I would like to know additional details if any regarding the issue.

Best Regards
