### ISSUE TITLE
[Bug]: Error to clear value from custom Attribute Dropdown

### ISSUE THREAD

**Issue by rochaalexandre** [saleor/saleor-dashboard#4933]
### Description of the issue

When attempting to clear the value of a custom attribute with the input type set to "dropdown" for a product, the operation fails.
![saleor-issue](https://github.com/saleor/saleor-dashboard/assets/28936892/1331b45d-c2da-45c0-83a5-7899f1772328)

### Steps to reproduce the problem

Steps to Reproduce:

- Create a custom attribute with the value required set to false and the type set to "Dropdown."
- Assign some value options to this attribute.
- Assign this attribute to a product type.
- Access the product details.
- Add a value to the custom attribute with the input type set to "dropdown" for the product.
- Attempt to clear the value previously added.

### What did you expect to happen?

Observed Behavior:
The dashboard sends the attribute as value: [ null ], which causes an error in the backend.

Expected Behavior:
Based on the behavior of other input types, when clearing the value of an attribute, the dashboard should only send the attribute ID in the update request. The dropdown type should follow the same behavior to avoid backend errors.

### Additional information

Custom attributes with other input types only send the attribute ID when their values are removed during an update.
This inconsistent behavior leads to the backend breaking when handling dropdown attribute updates.

### Environment

Browser and version: Chrome Version 125.0.6422.141 (Official Build) (64-bit)
Dashboard version: 3.19.4
Core version: 3.19

**Comment by simon-online** [comment]
Yes, I'm getting this issue also on the following:

Dashboard v3.19.8
Core v3.19.46

Hopefully this can be resolved soon as I have a client that's wanting to use this functionality.

**Comment by Cloud11PL** [comment]
Hi,

thanks for creating the issue. We will take a look 🙂

**Comment by poulch** [comment]
@rochaalexandre fix for this bug has been released: https://github.com/saleor/saleor-dashboard/releases/tag/3.20.11
