### ISSUE TITLE
[Bug]: Run saleor-dashboard at localhost

### ISSUE THREAD

**Issue by PhuongT1** [saleor/saleor-dashboard#5015]
### Description of the issue

I cloned source:  https://github.com/saleor/saleor-dashboard
but when I  run code at localhost

### Steps to reproduce the problem

I cloned source:  https://github.com/saleor/saleor-dashboard
but when I  run code at localhost

### What did you expect to happen?

 browser have error: 'Not allowed to load local resource' when I access : http://localhost:9000/
Can you hep me ? 

### Environment

Dashboard version

**Comment by Cloud11PL** [comment]
Hi,

Do you have a local instance of Saleor running?

If you want to run Saleor locally (Saleor Core + Dashboard) use https://github.com/saleor/saleor-platform

**Comment by jigs1212** [comment]
[Use the following installation guide to setup saleor platform locally.](https://docs.saleor.io/setup/docker-compose) 
1. Make sure to comment dashboard section inside `saleor-platform/docker-compose.yml`.
2. Update/create `.env` of `saleor-dashboard` project as below.

```
API_URL=http://localhost:8000/graphql/
APP_MOUNT_URI=/
# APPS_MARKETPLACE_API_URL=https://apps.saleor.io/api/v2/saleor-apps
LOCALE_CODE="EN"
DEMO_MODE=false

MAILPITURL=xxxx #For playwright

E2E_USER_NAME=xxxx
E2E_USER_PASSWORD=xxxx
E2E_PERMISSIONS_USERS_PASSWORD=xxxx
BASE_URL=http://localhost:9000/```

**Comment by tjl521** [comment]
But I need to run the saleor-dashboard project separately, not the saleor-platform project. How can I resolve this issue?

`Not allowed to load local resource: file:///D:/test/saleor-dashboard-main/src/index.tsx`

**Comment by oqildev** [comment]
I have also this issue.
Not allowed to load local resource: file:///D:/Devsymfony/saleor-dashboard/src/index.tsx
I have own server and own api_url.
I just want to run dashboard but not working. Dashboard running localhost:9000 but in browser blank screen.

**Comment by jigs1212** [comment]
> But I need to run the saleor-dashboard project separately, not the saleor-platform project. How can I resolve this issue?
> 
> `Not allowed to load local resource: file:///D:/test/saleor-dashboard-main/src/index.tsx`

You can stop the saleor dashboard from the docker and can run saleor dashboard locally, and update the .env as mentioned above.

**Comment by jigs1212** [comment]
> I have also this issue. Not allowed to load local resource: file:///D:/Devsymfony/saleor-dashboard/src/index.tsx I have own server and own api_url. I just want to run dashboard but not working. Dashboard running localhost:9000 but in browser blank screen.

Can you please share the errors from the console.

**Comment by oqildev** [comment]
![Screenshot_3](https://github.com/user-attachments/assets/0614defe-48e8-4989-8dec-372b063851d2)
![Screenshot_4](https://github.com/user-attachments/assets/3e3b097d-6297-4716-b27a-ec4912e88d14)

**Comment by tjl521** [comment]
> > 但我需要单独运行 saleor-dashboard 项目，而不是 saleor-platform 项目。我该如何解决这个问题？
> > `Not allowed to load local resource: file:///D:/test/saleor-dashboard-main/src/index.tsx`
> 
> 您可以从 docker 停止 saleor 仪表板并在本地运行 saleor 仪表板，并按照上面提到的方式更新 .env。

I did configure it this way, and the project started without any issues, but when I open it in the browser, this error is thrown, and there is no content on the page.

**Comment by tjl521** [comment]
> ![Screenshot_3](https://private-user-images.githubusercontent.com/172834060/365744437-0614defe-48e8-4989-8dec-372b063851d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzI1NjAsIm5iZiI6MTcyNTkzMjI2MCwicGF0aCI6Ii8xNzI4MzQwNjAvMzY1NzQ0NDM3LTA2MTRkZWZlLTQ4ZTgtNDk4OS04ZGVjLTM3MmIwNjM4NTFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwMTM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzFiZmEwNDM2NjE4OGFmZGRlMmY3ZTZhY2I1ZmFmNmJiNjAyZDBjMGE4OWYzYzRmY2YxOTg0OGQzZjIwYWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G8SKl4EjMGu05jGe76EblmF7nBb4iCxBcs8WvmPEvvE) ![Screenshot_4](https://private-user-images.githubusercontent.com/172834060/365744468-3e3b097d-6297-4716-b27a-ec4912e88d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzI1NjAsIm5iZiI6MTcyNTkzMjI2MCwicGF0aCI6Ii8xNzI4MzQwNjAvMzY1NzQ0NDY4LTNlM2IwOTdkLTYyOTctNDcxNi1iMjdhLWVjNDkxMmU4OGQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwMTM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzI2OGUwZmMwMmVmZjk4MzI5NjQ1Yzc1MWViNWI5MzI4Yzg3ZTdjMzI4OTMzNzg5OTY4ZmRhNjQwMzY3YzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wtVzb1PgqKPfzzcl7gURl-FdAKpFiNnrsBkvZl_htGM)

My error message is the same as this.

**Comment by PhuongT1** [comment]
> > > 但我需要单独运行 saleor-dashboard 项目，而不是 saleor-platform 项目。我该如何解决这个问题？
> > > `Not allowed to load local resource: file:///D:/test/saleor-dashboard-main/src/index.tsx`
> > 
> > 
> > 您可以从 docker 停止 saleor 仪表板并在本地运行 saleor 仪表板，并按照上面提到的方式更新 .env。
> 
> I did configure it this way, and the project started without any issues, but when I open it in the browser, this error is thrown, and there is no content on the page.

**Comment by PhuongT1** [comment]
> ![Screenshot_3](https://private-user-images.githubusercontent.com/172834060/365744437-0614defe-48e8-4989-8dec-372b063851d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDQzNTIsIm5iZiI6MTcyNTk0NDA1MiwicGF0aCI6Ii8xNzI4MzQwNjAvMzY1NzQ0NDM3LTA2MTRkZWZlLTQ4ZTgtNDk4OS04ZGVjLTM3MmIwNjM4NTFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwNDU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzdiNzZjY2IzODEyZjIyMGZkOGQwNzUyMDNiNGU2MjNhMTQyNWRmMzMxYWMzYmYxZjExNjgyYjA5ZTk3NTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YePw8my0HpDfOdtTgHuqH8fuHQuuwFrMwi_T9m-5cZQ) ![Screenshot_4](https://private-user-images.githubusercontent.com/172834060/365744468-3e3b097d-6297-4716-b27a-ec4912e88d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDQzNTIsIm5iZiI6MTcyNTk0NDA1MiwicGF0aCI6Ii8xNzI4MzQwNjAvMzY1NzQ0NDY4LTNlM2IwOTdkLTYyOTctNDcxNi1iMjdhLWVjNDkxMmU4OGQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwNDU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjAxNzI5NjQxY2UzNWFkMWVhNGZiYmU2NGFkYTlhOTM4OTAwZmY5YjhhZTM3ZDdlZWZiZTVkMTRjODkzY2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VsDzh8kYwW8twnS8tG0nwA0r_iwMccymJLNtbdOBu9A)

Hi oqildev, 
"This happens because you're running the Saleor dashboard on Windows; it doesn't occur on a MacBook. To fix this issue, it's very simple: in the vite.config.js file, change entry: path.resolve(__dirname, "src", "index.tsx") to entry: "/index.tsx". It will work fine."
