### ISSUE TITLE
[Bug]: Is there no way for superusers to log into dashboard

### ISSUE THREAD

**Issue by RuoCJ** [saleor/saleor-dashboard#5038]
I started saleor's back-end service locally, created superuser, and then launched dashboard, but I couldn't log in to dashboard with the superuser account I created. Why？

**Comment by Cloud11PL** [comment]
Hi, could you please provide more details? What is the error that is returned? What's the response from API?

**Comment by RuoCJ** [comment]
> Hi, could you please provide more details? What is the error that is shown? What's the response from API?

Ouch! I'm sorry for not solving this problem in time. I've been so busy lately, I've forgotten. I have solved the problem. The reason is that when I created the superuser, I randomly wrote an email address, so I couldn't log in when I logged in to the dashboard. The solution is to change the superuser's mailbox to the correct one, such as Google Mail
