### ISSUE TITLE
After removing group which gives me manage staff I see "Staff settings" in the configuration panel 

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor-dashboard#504]
### What I'm trying to achieve
After removing group which gives me manage staff I see "Staff settings" in the configuration panel, but when I am trying to open any of staff-related page, I get an error one.

### Steps to reproduce the problem
Perform these steps on the database after populatedb
1. Log in as admin (superuser)
2. Create a group with manage staff (let's name it Test group) and add some of the users to this group (not superuser)
3. Log out
4. Log in as a user from a group with manage staff
5. Remove Test group
6. Go to the configuration page
7. Try to open `permission groups` or `staff members` page

### What I expected to happen
I shouldn't be able to open the configuration panel, and I should get some other message when I am trying to reach those pages. The message should inform me that I don't have access to those pages.

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/80464567-4a8bb600-893a-11ea-9d18-3d2f88c41300.png)
![image](https://user-images.githubusercontent.com/40886528/80464662-6abb7500-893a-11ea-94f2-109260d7da9b.png)

**Comment by krzysztofwolski** [comment]
Thats not a bug. Thats the feature!

When trying accessing page you do not have access, you should be presented with 404 error instead of permission denied.

**Comment by IKarbowiak** [comment]
I can't agree with you. I should be redirected to another page that I have access to, after removing the group. I don't want to see the error page after removing the group.

**Comment by eCzerniak** [comment]
Fixed.
