### ISSUE TITLE
After logging out from admin and log in as the different user I get an error page

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor-dashboard#505]
### What I'm trying to achieve
After logging out from admin and log in as the different user I get an error page. It happens when just before log out you are on a page that is not accessible by the second user.

### Steps to reproduce the problem
1. Log in as admin
2. Go to configuration panel, open `permission group` page
3. Log out
4. Log in as different staff user who doesn't have manage staff permission

### What I expected to happen
I shouldn't get an error page. I should be redirected to some page where I have access to, e.g. home page.

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/80466524-f9c98c80-893c-11ea-9b62-12727da9e034.png)

**Comment by krzysztofwolski** [comment]
Same as https://github.com/mirumee/saleor-dashboard/issues/504#issuecomment-621048163

**Comment by IKarbowiak** [comment]
The same here, it should be fixed in my opinion, because when I log in as a different user I want to be on home page, not on page to which I don't have access. It's not a situation where I open this page on purpose. After log in it's opening the last site visited in the dashboard and doesn't care be which user. As a different user, I should get the home page.

**Comment by eCzerniak** [comment]
Fixed.
