### ISSUE TITLE
[Bug]: Assign attribute window shows values twice

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-dashboard#5066]
### Description of the issue

<img width="719" alt="image" src="https://github.com/user-attachments/assets/47fe3e91-9280-478e-afec-5d8e9d8be564">

### Steps to reproduce the problem

assign attribute to type

### What did you expect to happen?

...

### Environment

dashboard v3.20.2
core v3.20.5

**Comment by slawekmarszalek** [comment]
Fix for this issue has been released.
