### ISSUE TITLE
[Bug]: Can't select customer address for Draft Order

### ISSUE THREAD

**Issue by pawelromanskidajar** [saleor/saleor-dashboard#5129]
### Description of the issue

For a draft order with selected customer (but empty address) it is impossible to select address. I have checked this on fresh Saleor Cloud Instance

### Steps to reproduce the problem

1. Go to Order > Drafts and Create Order
2. Select any channel
3. Add one or more products
4. Edit customer (select any customer)
5. IMPORTANT: When "Change address for order" dialog appears, click outside of it - to close it
6. Edit Shipping address
7. Use one of customer addresses > Continue

We reach the bug -> clicking on "Select" doesn't do anything. No errors in console, no network requests

### What did you expect to happen?

It should be possible to select address for draft order

### Additional information

It is important that bug happens when customer is selected and addresses are not
![image](https://github.com/user-attachments/assets/c886b867-b455-4fb1-a073-0d8f34e9b23a)
Then select button doesn't work
![image](https://github.com/user-attachments/assets/93b0bbe5-1ea5-49c8-8a1a-07a46e5364c8)

### Environment

Browser and version: Google Chrome 127.0.6533.120
OS and version: Windows 11
Dashboard version: 3.20.6
Core version: 3.20.18

**Comment by andrzejewsky** [comment]
Hey, thanks for reporting. 

I was testing this right now but I was not able to reproduce that. I followed all your steps. Have you tried recent version of the dashbaord? (3.20.10)

**Comment by pawelromanskidajar** [comment]
Hey, I have checked now on the latest version and it seems to be fix indeed. Thanks for checking!
