### ISSUE TITLE
[Bug]: Cant change password in UI

### ISSUE THREAD

**Issue by ibigbug** [saleor/saleor-dashboard#5247]
### Description of the issue

Clicking the "Save" button in the change password modal nothing happens.

see the attached video

https://github.com/user-attachments/assets/beeaa435-233b-4a0f-a121-864d600f458d

### Steps to reproduce the problem

0. Fresh install of saleor-platform(on k8s) https://github.com/saleor/saleor-platform/blob/main/docker-compose.yml
0.run db migration and createsuperuser
0. login with superuser just created
0. change password

### What did you expect to happen?

Password can be updated or at lease some network request being sent

### Environment

Browser and version: Edge / Firefox latest
OS and version: Windows 11
Dashboard version: latest docker image
Core version: 3.20 docker image

**Comment by Cloud11PL** [comment]
Hi, thanks for reporting. We're going to look into this :)

**Comment by Cloud11PL** [comment]
Fixed with https://github.com/saleor/saleor-dashboard/releases/tag/3.20.19
