### ISSUE TITLE
No error message when trying to create another default shipping zone

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-dashboard#543]
Shipping zone is "default" when selecting the "Rest of the world" option is "Assign Countries" modal. I can have only one default shipping zone. When I'm trying to create another one there is no error message displayed to the user informing what happened:

![image](https://user-images.githubusercontent.com/5421321/83250872-0d207f80-a1a9-11ea-91f8-a86575b1966e.png)

The API response with error code that is not handled in UI:
```
{"data": {"shippingZoneUpdate": {"errors": [{"code": "ALREADY_EXISTS", "field": "default", "__typename": "ShippingError"}], "shippingZone": null, "__typename": "ShippingZoneUpdate"}}}
```

Steps to reproduce:
1. Create a shipping zone and mark it as "Rest of the world" in the "Assign country" modal.
2. Try to create another one with the same settings. The button goes to "Error" state but no message is displayed.

**Comment by eCzerniak** [comment]
Fixed.
