### ISSUE TITLE
Default shipping zone not created in the "create" view

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-dashboard#550]
### What I'm trying to achieve
I'm trying to create a default shipping zone. Configuration > Shipping Methods > Create New Shipping Zone

### Steps to reproduce the problem
1. Go to "Create New Shipping Zone" view.
2. Open "Assign Countries" modal and select "Rest of the world".
3. Click "Assign countries"
4. Click "Save"
5. The shipping zone gets created but the "default" option is not set.

It looks like API doesn't send the "default" field in the "create" mutation.

### What I expected to happen
The "default" option should be enabled.

**Comment by eCzerniak** [comment]
It is fixed now.
https://github.com/saleor/saleor-dashboard/pull/1672
