### ISSUE TITLE
Dashboard > Configuration > Navigation  > Navbar : issue reordering Navbar > Menu Items

### ISSUE THREAD

**Issue by onelsonic** [saleor/saleor-dashboard#654]
Trying to reorder the menu items in the Navbar, then save.
Reordering doesn't work sometimes.

For example moving the 2nd category to the 1st position is not saved.

**Comment by KerryMahne** [comment]
Hey! As it turns out I've got a fix for this @maarcingebala !
I have a local branch ready for this, since I've fixed it for our project too. Could you perhaps give me access so I can open a PR for this?

**Comment by maarcingebala** [comment]
Hey @KerryMahne, sounds great! To open a pull request you can create a fork of the project, create a branch with the changes and then open a pull request. With a fork, you don't need any special permission to open a PR.

**Comment by KerryMahne** [comment]
Alright I've tried to fix it, but it doesn't seem to budge...
I think it could be a backend issue, but I am not proficient enough in Django to be able to debug from there. Check out my PR, it sends the whole new order to the backend, yet the first one still doesn't update.

**Comment by eCzerniak** [comment]
@KerryMahne can you check now on the newest version? We made some changes.

**Comment by eCzerniak** [comment]
@KerryMahne I'm closing this ticket. If issue will occur please reopen this ticket or create new one. 
Regards!
